parameters:
  - name: environment
    type: string
  - name: sourcePath
    type: string
    #default: "\\vmwclnwosdusc01\e$\OPS_Secure_Dev01"  # Default value, can be overridden
  - name: destinationRootPath
    type: string
   #default: "C:\Backup"  # Default value, can be overridden

stages:
- stage: ${{ parameters.environment }}
  displayName: 'Release ${{ parameters.environment }}'
  jobs:
  - deployment:
    displayName: 'Release_${{ parameters.environment }}'
    environment: 
      name: ${{ lower(parameters.environment) }}
      resourceType: virtualMachine
    strategy:
      runOnce:
        deploy:  
          steps:  

          - task: PowerShell@2
            displayName: backup
            inputs:
              targetType: 'inline'
              script: |
                # Define the source and destination paths from pipeline variables
                $sourcePath = "${{ parameters.sourcePath }}"
                $destinationRootPath = "${{ parameters.destinationRootPath }}"
                
                # Get the current date and time to create a unique folder name
                $dateTime = Get-Date -Format "yyyyMMdd-HHmmss"
                $destinationFolderPath = Join-Path -Path $destinationRootPath -ChildPath "Backup_$dateTime"
                
                # Create the new destination folder
                New-Item -Path $destinationFolderPath -ItemType Directory
                
                # Move all files and directories from the source path to the new destination folder
                Get-ChildItem -Path $sourcePath | ForEach-Object {
                    Copy-Item -Path $_.FullName -Destination $destinationFolderPath -Recurse -Force
                }
                
                # Optional: Confirm the operation is completed
                Write-Host "All files and folders have been moved to $destinationFolderPath"

#          - task: PowerShell@2
#            displayName: clean old repos
#            inputs:
#              targetType: 'inline'
#              script: 'Remove-Item -Path "${{ parameters.sourcePath }}\*" -Recurse -Force'
              
          - task: PowerShell@2
            displayName: copy content
            inputs:
              targetType: 'inline'
              script: 'Copy-Item -Path "$(Pipeline.Workspace)\drop\Content\C_C\agent-ic-admin-dev\_work\2\s\HM.Operations.Secure.Web\obj\Local\Package\PackageTmp" -Destination "$(Pipeline.Workspace)" -Recurse -Force'

          - task: PowerShell@2
            displayName: exclude .config files
            inputs:
              targetType: 'inline'
              script: |
                $directoryPath = "$(Pipeline.Workspace)\PackageTmp"
                $configFiles = Get-ChildItem -Path $directoryPath -Recurse -Filter "*.config"
                foreach ($file in $configFiles) {
                  Remove-Item -Path $file.FullName -Force
                }
                Write-Output "All .config files have been deleted."

          - task: PowerShell@2
            displayName: end
            inputs:
              targetType: 'inline'
              script: 'Copy-Item -Path "$(Pipeline.Workspace)\PackageTmp\*" -Destination C:\azure-devops-deployment -Recurse -Force'
          
          - task: PowerShell@2
            displayName: clean old repos
            inputs:
              targetType: 'inline'
              script: 'echo "$(System.DefaultWorkingDirectory)"'

          - task: PowerShell@2
            displayName: SQL commands
            inputs:
              filePath: '$(System.Build.Repository.LocalPath)/scripts/sql-commands.ps1'
              arguments: '-rootDir "$(System.DefaultWorkingDirectory)"'
