stages:
- stage: Build
  displayName: Build and Test  
  jobs:
    - job: Build
      displayName: Build
      steps:
      - task: NuGetToolInstaller@1
      - task: NuGetAuthenticate@1
      - task: NuGetCommand@2
        inputs:
         command: 'restore'
         restoreSolution: '$(solution)'
         feedsToUse: 'config'
         nugetConfigPath: 'AzureNuget.config'   
      - task: VSBuild@1
        inputs:
         solution: '$(solution)'
         msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=FileSystem  /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
      #- task: VSTest@2
        #inputs:
          #platform: '$(buildPlatform)'
          #configuration: '$(buildConfiguration)'             
      - task: PublishBuildArtifacts@1
        inputs:
         PathtoPublish: '$(build.artifactStagingDirectory)'
         ArtifactName: 'drop'
         publishLocation: 'Container'