parameters:
  - name: environment
    type: string

stages:
- stage: ${{ parameters.environment }}
  displayName: 'Release ${{ parameters.environment }}'
  jobs:
  - deployment:
    displayName: 'Release_${{ parameters.environment }}'
    environment: 
      name: ${{ lower(parameters.environment) }}
      resourceType: virtualMachine
    strategy:
      runOnce:
        deploy:
          steps:
            - powershell: |
                Write-Host "Testing steps for deployment"
              displayName: 'Powershell Command'
              errorActionPreference: 'Continue'
            
            - task: DownloadPipelineArtifact@2
              inputs:
                buildType: 'current'
                artifactName: 'drop'
#                targetPath: '$(System.ArtifactsDirectory)'
                targetPath: 'C:\azure-devops-deployment'
            - task: PowerShell@2
              displayName: backup
            inputs:
              targetType: 'inline'
              script: |
                # Define the source and destination paths
                $sourcePath = "\\vmwclnwosdusc01\devops-share"
                $destinationRootPath = "C:\Backup"
                
                # Get the current date and time to create a unique folder name
                $dateTime = Get-Date -Format "yyyyMMdd-HHmmss"
                $destinationFolderPath = Join-Path -Path $destinationRootPath -ChildPath "Backup_$dateTime"
                
                # Create the new destination folder
                New-Item -Path $destinationFolderPath -ItemType Directory
                
                # Move all files and directories from the source path to the new destination folder
                Get-ChildItem -Path $sourcePath | ForEach-Object {
                    Move-Item -Path $_.FullName -Destination $destinationFolderPath -Force
                }
                
                # Optional: Confirm the operation is completed
                Write-Host "All files and folders have been moved to $destinationFolderPath"
            - task: PowerShell@2
              displayName : clean old repos
              inputs:
                targetType: 'inline'
                script: 'Remove-Item -Path "\\vmwclnwosdusc01\devops-share\*" -Recurse -Force'
            - task: PowerShell@2
              displayName : archive
              inputs:
                targetType: 'inline'
                script: 'Expand-Archive -Path "C:\azure-devops-deployment\HM.Operations.Secure.Web.zip" -DestinationPath "C:\azure-devops-deployment" -Force'
            - task: PowerShell@2
              displayName : copy content
              inputs:
                targetType: 'inline'
                script: 'Copy-Item -Path "C:\azure-devops-deployment\Content\C_C\agent-ic-admin-dev\_work\2\s\HM.Operations.Secure.Web\obj\Local\Package\PackageTmp" -Destination "C:\azure-devops-deployment" -Recurse -Force'
            - task: PowerShell@2
              displayName: end
              inputs:
                targetType: 'inline'
                script: 'Copy-Item -Path "C:\azure-devops-deployment\PackageTmp\*" -Destination \\vmwclnwosdusc01\devops-share -Recurse -Force'
             task: PowerShell@2
              displayName : clean repo
              inputs:
                targetType: 'inline'
                script: 'Remove-Item -Path "C:\azure-devops-deployment\*" -Recurse -Force'