stages:
- stage: Build
  displayName: Build and Test  
  jobs:
    - job: Build
      displayName: Build
      steps:
      - task: NuGetToolInstaller@1
      - task: NuGetAuthenticate@1
      - task: NuGetCommand@2
        inputs:
         command: 'restore'
         restoreSolution: '$(solution)'
         feedsToUse: 'config'
         nugetConfigPath: 'AzureNuget.config'   
      - task: VSBuild@1
        inputs:
         solution: '$(solution)'
         msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
      #- task: VSTest@2
        #inputs:
          #platform: '$(buildPlatform)'
          #configuration: '$(buildConfiguration)' 
      - task: PowerShell@2
        displayName : archive
          inputs:
            targetType: 'inline'
            script: 'Expand-Archive -Path "$(build.artifactStagingDirectory)\HM.Operations.Secure.Web.zip" -DestinationPath "$(build.artifactStagingDirectory)" -Force' #  "C:\azure-devops-deployment\HM.Operations.Secure.Web.zip" -DestinationPath "C:\azure-devops-deployment"            
      - task: PowerShell@2
        displayName : rmove-zip-file
          inputs:
            targetType: 'inline'
            script: 'Remove-Item -Path "$(build.artifactStagingDirectory)\HM.Operations.Secure.Web.zip" -Force'
      - task: PublishBuildArtifacts@1
        inputs:
         PathtoPublish: '$(build.artifactStagingDirectory)\M.Operations.Secure.Web\obj\Local\Package\PackageTmp'
         ArtifactName: 'drop'
         publishLocation: 'Container'