parameters:
  - name: environment
    type: string

stages:
- stage: ${{ parameters.environment }}
  displayName: 'Release ${{ parameters.environment }}'
  jobs:
  - deployment:
    displayName: 'Release_${{ parameters.environment }}'
    environment: 
      name: ${{ lower(parameters.environment) }}
      resourceType: virtualMachine
    strategy:
      runOnce:
        deploy:
          steps:
            - powershell: |
                Write-Host "Testing steps for deployment"
              displayName: 'Powershell Command'
              errorActionPreference: 'Continue'
            
            - task: DownloadPipelineArtifact@2
              inputs:
                buildType: 'current'
                artifactName: 'drop'
#                targetPath: '$(System.ArtifactsDirectory)'
                targetPath: 'C:\azure-devops-deployment'