using HedgeMark.SwiftMessageHandler.Model;
using NUnit.Framework;

namespace HedgeMark.SwiftMessageHandler.Tests
{
    [TestFixture]
    public class SwiftMT094MessageParserTest
    {

        [Test]
        public void ParseMt094BroadCastFromStringTest1()
        {
            var fin = @"{1:F01HMRKUS33SXXX0012000073}{2:O0941529190715MTMTXXXX9XXX00504263741907151129S}{4:{135:U}{136:B74929}{129:01/01}{130:/01/BANK
/ 01 / OPERATIONAL}{134:UBPGCHGG
96-98 RUE DU RHONE
GENEVE}{312:DEAR ALL
.
IN COMPLEMENT TO BROADCAST NUMBER 07330 SENT EARLIER THIS MORNING
PLEASE NOTE BIC UBPGCHGE DOES NOT SUPERSEDE EXISTING
BIC UBPGCHGG.
.
EACH ENTITY DEEMED TO EXCHANGE SWIFT MESSAGES WITH UBPGCHGE WILL
BE ADVISED IN DUE TIME AND WILL BE PROVIDED WITH FULL DETAILS ON
A BILATERAL BASIS.
.
PLEASE DO NOT CHANGE ANYTHING TO THE ACTUAL SWIFT SETUP UNTIL
FURTHER NOTICE.
.
FOR ANY QUESTIONS, PLEASE LIAISE WITH BANKINGRELATIONS(AT)UBP.CH
.
BEST REGARDS
BANKING RELATIONS
UNION BANCAIRE PRIVEE, UBP SA}}{5:{CHK:921F5743B90F}{SYS:1528190715UBPGCHGGAXXX2093886116}}";


            var sm = SwiftMessage.Parse(fin);

            Assert.IsFalse(sm.IsAck());
            Assert.IsFalse(sm.IsServiceMessage21());
            Assert.AreEqual(@"DEAR ALL
.
IN COMPLEMENT TO BROADCAST NUMBER 07330 SENT EARLIER THIS MORNING
PLEASE NOTE BIC UBPGCHGE DOES NOT SUPERSEDE EXISTING
BIC UBPGCHGG.
.
EACH ENTITY DEEMED TO EXCHANGE SWIFT MESSAGES WITH UBPGCHGE WILL
BE ADVISED IN DUE TIME AND WILL BE PROVIDED WITH FULL DETAILS ON
A BILATERAL BASIS.
.
PLEASE DO NOT CHANGE ANYTHING TO THE ACTUAL SWIFT SETUP UNTIL
FURTHER NOTICE.
.
FOR ANY QUESTIONS, PLEASE LIAISE WITH BANKINGRELATIONS(AT)UBP.CH
.
BEST REGARDS
BANKING RELATIONS
UNION BANCAIRE PRIVEE, UBP SA",sm.GetFieldValue("312"));
        }

    }
}
