include:
  - project: 'glb/glb-01/gl-templates'
    ref: master
    file: '/gitlab-ci/dotnetfw-ci-common-core.yml'

VM Deployment:
  extends: .ansible_deploy_core
  rules:
    - if: '$CI_ENVIRONMENT_NAME == "test" && $CI_BUILD_REF_NAME == "develop"'
  before_script:
    - |
      export JDK_ANSIBLE_JOB_TEMPLATE=$JDK_ANSIBLE_JOB_TEMPLATE_TEST
      export DEPLOYMENT_HOSTS=$DEPLOYMENT_HOSTS_TEST
      echo $DEPLOYMENT_HOSTS_TEST
      echo $JDK_ANSIBLE_OPERATOR_ID
      trap "EDP_ANSIBLE_ENV=ansibletower-nonprod" DEBUG
  stage: deploy

VM Deployment QA:
  extends: .ansible_deploy_core
  rules:
    - if: '$CI_ENVIRONMENT_NAME == "test" && $CI_BUILD_REF_NAME == "release"'
  before_script:
    - |
      export JDK_ANSIBLE_JOB_TEMPLATE=$JDK_ANSIBLE_JOB_TEMPLATE_QA
      export DEPLOYMENT_HOSTS=$DEPLOYMENT_HOSTS_QA
      echo $DEPLOYMENT_HOSTS_QA
      echo $JDK_ANSIBLE_OPERATOR_ID
      trap "EDP_ANSIBLE_ENV=ansibletower-nonprod" DEBUG
  stage: deploy  

Build: 
  extends: .dotnetfw4x_build_core
  rules:
    - if: '$CI_ENVIRONMENT_NAME == "test" && $CI_BUILD_REF_NAME == "release"'
      variables:
        configuration: "QA"
    - when: always  

Upload_artifact:
  extends: .Dotnetfw_upload_artifact
  rules:
    - if: '$CI_BUILD_REF_NAME == "develop" || $CI_BUILD_REF_NAME == "release"'
  stage: publish  

Defendbot_scan:
  extends: .Defendbot_scan
  rules:
    - if: $CI_BUILD_REF_NAME == "develop"
  stage: validate

SonarCheck:
  extends: .dotnetfw4x_sonar_check_core
  rules:
    - if: $CI_BUILD_REF_NAME == "develop"
  before_script:
    - |
      export GLB_COMMON_NO_TEST=yes
  stage: check

variables:
#  GLB_COMMON_NO_TEST: 'yes'
#  GLB_COMMON_NO_BUILD: 'yes'
 ENABLE_ANSIBLE_DEPLOYMENT: 'yes'
 GIT_STRATEGY: clone
 APPSCAN_INCLUDE_FILENAMES_PATTERN: '*'
 APPSCAN_MNEMONIC: 'DMO'
 APPSCAN_PROFILENAME: '#VRA - DMO - HedgeMark Managed Account Operations'
 NEXUS_ARTIFACT_EXTENSION: 'zip'
 SOURCE_CODE_LANGUAGE: 'dotnet'
 DEPLOYMENT_HOSTS_TEST: 'wt81b10086tv00.ams.bnymellon.net:wt81b10085tv00.ams.bnymellon.net'
 DEPLOYMENT_HOSTS_QA: 'wt85b10254qv00.ams.bnymellon.net:wt85b10255qv00.ams.bnymellon.net:wc08a10003pv00.ams.bnymellon.net:ams.bnymellon.net'
 VM_PLATFORM: 'windows'
 OPERATOR_ID: 'dmum76m'
 CI_ENVIRONMENT_NAME: 'test'
 JDK_ANSIBLE_JOB_TEMPLATE_TEST: '72272'
 JDK_ANSIBLE_JOB_TEMPLATE_QA: '73734'
 JDK_ANSIBLE_AWX_TOKEN: 'SEFGYZmdbzSfbb6D118BpQBeCdy7q7'
 JDK_ANSIBLE_OPERATOR_ID: 'xbbn39n'
 JDK_ANSIBLE_AWX_URL: 'https://ansibletower-nonprod.bnymellon.net'
 NEXUS_REPO_ID: 'd-BNYMellon-snapshots'
 NEXUS_GROUP: 'dmo.bnym'
 NEXUS_ARTIFACT: 'HM-Ops-Secure'
 NEXUS_ARTIFACT_VERSION: '0.0.1-SNAPSHOT'
#  APPSCAN_REPOSITORY_ID: 'd-BNYMellon-snapshots'
 