# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger: none

pool:
  name: "platform-application-agent-pool"


parameters:
  - name: environment
    displayName: Environment
    values:
      - Development
      - Test1
      - Test2
      - QA1
      - QA2
      - Production

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Local'

stages:
  - template: pipeline-templates/azure-build.yml
  - template: pipeline-templates/azure-release.yml
    parameters:
      environment: ${{ parameters.environment }}
  - stage: deployement
    displayName: deployment
    jobs:
      - job: powershell
        steps :
          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: |
                echo %WORKSPACE%
                nuget sources
                nuget config -set repositoryPath="%WORKSPACE%\packages"
                nuget restore "HMOSecureWeb.sln" -NoCache -PackagesDirectory packages
#                sc.exe config $serviceName obj= "$Username" password= "$Password"
          - task: PowerShell@2
            inputs:
              filePath: '$(System.DefaultWorkingDirectory)/scripts/sql-commands.ps1 -rootDir "$(System.DefaultWorkingDirectory)"'
                

