# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger: none

pool:
  name: "platform-application-agent-pool"



parameters:
  - name: environment
    displayName: Environment
    values:
      - Development
      - Test1
      - Test2
      - QA1
      - QA2
      - Production

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Local'
  group: Development

stages:
  - template: pipeline-templates/azure-build.yml        
  - template: pipeline-templates/azure-release.yml
    parameters:
      environment: ${{ parameters.environment }}  # Environment
      sourcePath: ${{ variables.sourcePath }}     # Fetch the sourcePath from the variable group
      destinationRootPath: ${{ variables.destinationRootPath }}  # Fetch the destinationRootPath from the variable group
  - stage: deployement
    displayName: deployment
    jobs:
      - job: powershell
        steps :
          - task: PowerShell@2
            displayName: Service Account Connection and Restart    
            inputs:
              targetType: 'inline'
              script: |
                # Update service to use gMSA
                sc.exe config "vstsagent.Innocap.platform-ic-admin-dev.platform-agent01" obj= "innocap\gmsa-icappsvc01$"
                
                # Restart the service to apply changes
                #Restart-Service -Name "vstsagent.Innocap.platform-ic-admin-dev.platform-agent01" -Force
                
                # Output success message
                #Write-Host "Service has been successfully configured and restarted."

          - task: PowerShell@2
            displayName: SQL commands
            inputs:
              filePath: '$(System.DefaultWorkingDirectory)/scripts/sql-commands.ps1'
              arguments: '-rootDir "$(System.DefaultWorkingDirectory)"'

                

