# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger: none

pool:
  name: "pipeline-cu-developers"
  demands:
  - Agent.OS -equals Windows_NT

parameters:
  - name: environment
    displayName: Environment
    values:
      - Development
      - Test1
      - Test2
      - QA1
      - QA2
      - Production

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Local'

stages:
  - template: pipeline-templates/azure-build.yml
  - template: pipeline-templates/azure-release.yml
    parameters:
      environment: ${{ parameters.environment }}