---
 
- hosts: all
  gather_facts: 'true'
  vars:

  tasks:
    - name: download artifact from Nexus
      win_get_url:
        url: http://nexus.bnymellon.net/nexus/service/local/artifact/maven/redirect?r={{ repo }}&g={{ group }}&a={{ artifact }}&v={{ version }}&e={{ extension }}
        dest: "{{nexus_code_available_path}}/artifacts.zip"
    
    - name: Extract in VM Machine
      win_unzip:
        src:  "{{nexus_code_available_path}}/artifacts.zip"
        dest:  "{{nexus_code_available_path}}/artifacts"
        remote_src: yes
        delete_archive: yes  

    - name: Assinging backup folder value to variable
      set_fact:
        backup_dir: "{{backupDir}}_{{ ansible_date_time.iso8601_basic_short }}"

    - name: Create backup folder
      win_file:
        path: "{{ backup_dir }}"
        state: directory

    - name: Delete Backup older than 7 days
      win_shell: 
        Get-ChildItem -Path {{backupfolderspath}} -Directory -recurse| where {$_.LastWriteTime -le $(get-date).AddDays(-7)} | Remove-Item -recurse -force

    - name: Copy htm file to directories
      win_copy:
        src: "{{ htmfile }}"
        dest: "{{ appDir01 }}"
        remote_src: yes
      when: appDir01 is defined

    - name: Copy htm file to directories
      win_copy:
        src: "{{ htmfile }}"
        dest: "{{ appDir02 }}"
        remote_src: yes
      when: appDir02 is defined

    - name: Copy htm file to directories
      win_copy:
        src: "{{ htmfile }}"
        dest: "{{ appDir03 }}"
        remote_src: yes
      when: appDir03 is defined    

    - name: Copy htm file to directories
      win_copy:
        src: "{{ htmfile }}"
        dest: "{{nexus_code_available_path}}/artifacts/"
        remote_src: yes
      when: appDir03 is defined    

    - name: call this task if backup copy of Existing Code
      win_copy:
        src: "{{ appDir01 }}"
        dest: "{{ backup_dir }}/{{dir01}}"
        remote_src: yes
      when: appDir01 is defined  

    - name: call this task if backup copy of Existing Code
      win_copy:
        src: "{{ appDir02 }}"
        dest: "{{ backup_dir }}/{{dir02}}"
        remote_src: yes
      when: appDir02 is defined

    - name: call this task if backup copy of Existing Code
      win_copy:
        src: "{{ appDir03 }}"
        dest: "{{ backup_dir }}/{{dir03}}"
        remote_src: yes    
      when: appDir03 is defined
    
    - name: "Clean Up Deploy Folder"
      win_file:
        path: "{{ appDir01 }}"
        state: absent
      when: appDir01 is defined

    - name: "Clean Up Deploy Folder"
      win_file:
        path: "{{ appDir02 }}"
        state: absent
      when: appDir02 is defined

    - name: "Clean Up Deploy Folder"
      win_file:
        path: "{{ appDir03 }}"
        state: absent
      when: appDir03 is defined
      
    - name: Creates directories
      win_file:
        path: "{{ appDir01 }}"
        state: directory
      when: appDir01 is defined  

    - name: Creates directories
      win_file:
        path: "{{ appDir02 }}"
        state: directory
      when: appDir02 is defined
      
    - name: Creates directories
      win_file:
        path: "{{ appDir03 }}"
        state: directory
      when: appDir03 is defined  
  
      
    - name: call this task to copy source code to Ops Deployment Path
      win_copy:
        src: "{{nexus_code_available_path}}/artifacts/"
        dest: "{{ appDir01 }}"
        remote_src: yes
      when: appDir01 is defined

    - name: call this task to copy source code to Ops Deployment Path
      win_copy:
        src: "{{nexus_code_available_path}}/artifacts/"
        dest: "{{ appDir02 }}"
        remote_src: yes
      when: appDir02 is defined

    - name: call this task to copy source code to Ops Deployment Path
      win_copy:
        src: "{{nexus_code_available_path}}/artifacts/"
        dest: "{{ appDir03 }}"
        remote_src: yes    
      when: appDir03 is defined

    - name: "Clean Up Test-Deploy Folder inside AnisbleDeployment"
      win_file:
        path: "{{nexus_code_available_path}}/artifacts/"
        state: absent
        
    - name: remove htm file from deployment folder
      win_file:
        path: "{{ appDir01 }}/app_offline.htm"
        state: absent
      when: appDir01 is defined 

    - name: remove htm file from deployment folder
      win_file:
        path: "{{ appDir02 }}/app_offline.htm"
        state: absent
      when: appDir02 is defined 

    - name: remove htm file from deployment folder
      win_file:
        path: "{{ appDir03 }}/app_offline.htm"
        state: absent
      when: appDir03 is defined   

    - name: Start IIS
      win_shell: |
        Restart-WebAppPool -Name {{dir01}}
      when: appDir01 is defined and cnj is not defined

    - name: Start IIS
      win_shell: |
        Restart-WebAppPool -Name {{dir02}}
      when: appDir02 is defined and cnj is not defined

    - name: Start IIS
      win_shell: |
        Restart-WebAppPool -Name {{dir03}}
      when: appDir03 is defined and cnj is not defined