---
 
- hosts: all
  gather_facts: 'true'
  vars:

  tasks:
    - name: download artifact from Nexus
      win_get_url:
        url: http://nexus.bnymellon.net/nexus/service/local/artifact/maven/redirect?r={{ repo }}&g={{ group }}&a={{ artifact }}&v={{ version }}&e={{ extension }}
        dest: "{{nexus_code_available_path}}/artifacts.zip"
    
    - name: Extract in VM Machine
      win_unzip:
        src:  "{{nexus_code_available_path}}/artifacts.zip"
        dest:  "{{nexus_code_available_path}}/artifacts"
        remote_src: yes
        delete_archive: yes

    - name: Assinging backup folder value to variable
      set_fact:
        backup_dir: "{{backupDir}}_{{ ansible_date_time.iso8601_basic_short }}"

    - name: Create backup folder
      win_file:
        path: "{{ backup_dir }}"
        state: directory

    - name: Stop IIS
      win_shell: |
        Stop-WebAppPool -Name {{dir01}}
      when: appDir01 is defined

    - name: Stop IIS
      win_shell: |
        Stop-WebAppPool -Name {{dir02}}
      when: appDir02 is defined

    - name: Stop IIS
      win_shell: |
        Stop-WebAppPool -Name {{dir03}}
      when: appDir03 is defined

    - name: call this task if backup copy of Existing Code
      win_copy:
        src: "{{ appDir01 }}"
        dest: "{{ backup_dir }}/{{dir01}}"
        remote_src: yes
      when: appDir01 is defined  

    - name: call this task if backup copy of Existing Code
      win_copy:
        src: "{{ appDir02 }}"
        dest: "{{ backup_dir }}/{{dir02}}"
        remote_src: yes
      when: appDir02 is defined

    - name: call this task if backup copy of Existing Code
      win_copy:
        src: "{{ appDir03 }}"
        dest: "{{ backup_dir }}/{{dir03}}"
        remote_src: yes    
      when: appDir03 is defined

    - name: call this task to copy source code to Ops Deployment Path
      win_copy:
        src: "{{nexus_code_available_path}}/artifacts/"
        dest: "{{ appDir01 }}"
        remote_src: yes
      when: appDir01 is defined

    - name: call this task to copy source code to Ops Deployment Path
      win_copy:
        src: "{{nexus_code_available_path}}/artifacts/"
        dest: "{{ appDir02 }}"
        remote_src: yes
      when: appDir02 is defined

    - name: call this task to copy source code to Ops Deployment Path
      win_copy:
        src: "{{nexus_code_available_path}}/artifacts/"
        dest: "{{ appDir03 }}"
        remote_src: yes    
      when: appDir03 is defined

    - name: call this task to copy web.config from backup to Ops Deployment Path
      win_copy:
        src: "{{ backup_dir }}/{{dir01}}/web.config"
        dest: "{{ appDir01 }}"
        remote_src: yes
      when: appDir01 is defined

    - name: call this task to copy web.config from backup to Ops Deployment Path
      win_copy:
        src: "{{ backup_dir }}/{{dir02}}/web.config"
        dest: "{{ appDir02 }}"
        remote_src: yes
      when: appDir02 is defined

    - name: call this task to copy web.config from backup to Ops Deployment Path
      win_copy:
        src: "{{ backup_dir }}/{{dir03}}/web.config"
        dest: "{{ appDir03 }}"
        remote_src: yes    
      when: appDir03 is defined
    
    - name: Start IIS
      win_shell: |
        Start-WebAppPool -Name {{dir01}}
      when: appDir01 is defined 

    - name: Start IIS
      win_shell: |
        Start-WebAppPool -Name {{dir02}}
      when: appDir02 is defined 

    - name: Start IIS
      win_shell: |
        Start-WebAppPool -Name {{dir03}}
      when: appDir03 is defined