stages:
- stage: InstallDependencies
  jobs:
  - job : InstallDotNet
    displayName: 'Install .NET Core SDK'
    pool:
      vmImage: 'windows-latest'

    steps:
      - task: UseDotNet@2
        inputs:
            version: 8.x
            performMultiLevelLookup: true
            includePreviewVersions: true

- stage: ExtractFiles
  jobs:
  - job : ExtractNant
    displayName: 'Extract NAnt'
    pool:
      vmImage: 'windows-latest'

    steps:
      - task: ExtractFiles@1
        inputs:
            archiveFilePatterns: 'nant.zip'
            destinationFolder: 'nant'
            cleanDestinationFolder: true
            overwriteExistingFiles: true

- stage: BuildWithNant
  jobs:
  - deployment: RunNantBuild
    displayName: 'Build with NAnt'
    pool:
      vmImage: 'windows-latest'
    environment:
      name: development 
    strategy:
      runOnce:
        deploy:
          steps:
          - script: nant\nant\bin\NAnt.exe -help