parameters:
  - name: environment
    displayName: environment
    values:
    - dev
    - qa

pool:
  name: Platform-OSC-${{ parameters.environment }}

stages:
- stage: BuildWithNant
  jobs:
  - job:
    steps:
    - task: PowerShell@2
      displayName: NUGET PACKAGES
      inputs:
        targetType: 'inline'
        script: |
          nuget sources
          nuget config -set repositoryPath="$(System.DefaultWorkingDirectory)\packages"
          nuget restore "HMOSecureWeb.sln" -NoCache -PackagesDirectory packages
    - script: E:\Software\nant-0.92\bin\nant.exe -buildfile:$(System.DefaultWorkingDirectory)/build/Application-${{ parameters.environment }}.build -verbose
      displayName: nant build
