stages:

- stage: InstallDependencies
  jobs:
  - job : InstallDotNet
    displayName: 'Install .NET Core SDK'
    pool:
      vmImage: 'windows-latest'

    steps:
      - task: UseDotNet@2
        inputs:
            version: 8.x
            performMultiLevelLookup: true
            includePreviewVersions: true
      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: 'dotnet add package NAnt --version 0.92.0'
      


