pool:
  name: pipeline-cu-developers 
stages:

- stage: BuildWithNant
  jobs:
  - deployment: RunNantBuild
    displayName: 'Build with NAnt'
    environment:
      name: development 
    strategy:
     runOnce:
       deploy: 
        steps:
        - task: PowerShell@2
          displayName: nuget restore
          inputs:
            targetType: 'inline'
            script: |
              echo $(System.DefaultWorkingDirectory)
              nuget sources
              echo sources done
              nuget config -set repositoryPath="$(System.DefaultWorkingDirectory)\packages"
              echo packages done
              nuget restore "$(System.DefaultWorkingDirectory)\HMOSecureWeb.sln"
#        - script: ping vmwclnwosdusc01.innocap.com
        - script: dir \\vmwclnwosdusc01\devops-share
        - script: nant -buildfile:$(System.DefaultWorkingDirectory)/build/Application-dev.build -verbose
          displayName: nant build

      


