pool:
  name: pipeline-cu-developers 
stages:

- stage: BuildWithNant
  jobs:
  - deployment: RunNantBuild
    displayName: 'Build with NAnt'
    environment:
      name: development 
    strategy:
     runOnce:
       deploy: 
        steps:
        - script: dir "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework"
          displayName: dir
        - task: NuGetCommand@2
          inputs:
            command: 'restore'
            restoreSolution: '**/*.sln'
            feedsToUse: 'select'
        - script: nant -buildfile:$(System.DefaultWorkingDirectory)/build/Application-dev.build -verbose

      


