pool:
  name: pipeline-cu-developers 
stages:

- stage: BuildWithNant
  jobs:
  - deployment: RunNantBuild
    displayName: 'Build with NAnt'
    environment:
      name: development 
    strategy:
      runOnce:
        deploy:
          steps:
          - script: nant -buildfile:$(Agent.BuildDirectory)/build/Application-dev.build
      


