stages:
- stage: InstallDependencies
  jobs:
  - job: InstallDotNet
    displayName: 'Install .NET Core SDK'
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: UseDotNet@2
      inputs:
        version: 8.x
        performMultiLevelLookup: true
        includePreviewVersions: true

- stage: ExtractFiles
  jobs:
  - job: ExtractNant
    displayName: 'Extract NAnt'
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: ExtractFiles@1
      inputs:
        archiveFilePatterns: 'nant.zip'
        destinationFolder: 'nant'
        cleanDestinationFolder: true
        overwriteExistingFiles: true

- stage: BuildWithNant
  jobs:
  - job: RunNantBuild
    displayName: 'Build with NAnt'
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          # Assuming NAnt is installed on the agent
          nant\bin\NAnt.exe -buildfile:build/Application-dev.build
