# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'windows-latest'

jobs:
- deployment: DeployWeb
  displayName: deploy Web App
  environment:
    name: 'development'
  strategy:
    runOnce:
      deploy:
        steps:
        - task: PowerShell@2
          inputs:
            filePath: '$(Build.SourcesDirectory)/Deploy/nant.ps1'
        - task: PowerShell@2
          inputs:
            targetType: 'inline'
            script: 'NAnt -buildfile build/Application-dev.build'
