#Azure Build and Release yaml for Operations Secure Environments 

trigger:
     none

parameters:
  - name: environment
    displayName: environment
    values:
    - dev
    - qa
    - test

stages:

- stage: BuildWithNant
  pool:
    name: Platform-OSC-${{ parameters.environment }}
  jobs:
  - job:
    steps:
    - task: PowerShell@2
      displayName: Restore Nuget Packages 
      inputs:
        targetType: 'inline'
        script: |
          nuget sources
          nuget config -set repositoryPath="$(System.DefaultWorkingDirectory)\packages"
          nuget restore "HMOSecureWeb.sln" -NoCache -PackagesDirectory packages
    - script: E:\Software\nant-0.92\bin\nant.exe -buildfile:$(System.DefaultWorkingDirectory)/build/Application-${{ parameters.environment }}.build -verbose
      displayName: BuildAndDeploy_OpsSecure in ${{ parameters.environment }}
