pool:
  name: pipeline-cu-developers 
stages:

- stage: BuildWithNant
  jobs:
  - job: RunNantBuild
    displayName: 'Build with NAnt'
    
    steps:
      - script: dir C:\Program Files (x86)
        displayName: dir
      - script: nant -buildfile:$(System.DefaultWorkingDirectory)/build/Application-dev.build -verbose

      


