stages:
- stage: BuildWithNant
  jobs:
  - deployment: RunNantBuild
    displayName: 'Build with NAnt'
    pool:
      vmImage: 'windows-latest'
    environment:
      name: development 
    strategy:
      runOnce:
        deploy:
          steps:
          - script: nant -buildfile:build/Application-dev.build
