IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME= 'hmsWires' AND COLUMN_NAME = 'Amount')
BEGIN
	UPDATE HM_WIRES.DBO.hmsWires SET SystemAmount=Amount WHERE SystemAmount =0.00;
END
GO