USE HM_WIRES;
IF (NOT EXISTS (SELECT * FROM sys.schemas WHERE name = 'DMABackup')) 
BEGIN
    EXEC ('CREATE SCHEMA [DMABackup] AUTHORIZATION [dbo]')
END
-------//hmsWiresS//--------
IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME= 'hmsWires_bkup_V36_0' AND TABLE_SCHEMA ='DmaBackup')
BEGIN
   SELECT * INTO DMABackup.hmsWires_bkup_V36_0 FROM hmsWires;
END
IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME= 'hmsWires' AND COLUMN_NAME = 'DummyClientFundId')
BEGIN
   ALTER TABLE hmsWires ADD DummyClientFundId BIGINT NULL;
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME= 'onBoardingAccount_bkup_V36_0' AND TABLE_SCHEMA ='DmaBackup')
BEGIN
   SELECT * INTO DMABackup.onBoardingAccount_bkup_V36_0 FROM onBoardingAccount;
END
IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME= 'onBoardingAccount' AND COLUMN_NAME = 'DummyClientFundId')
BEGIN
   ALTER TABLE onBoardingAccount ADD DummyClientFundId BIGINT NULL;
END
