IF NOT EXISTS(SELECT 8 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'CutOffTimeZone' AND TABLE_NAME = 'onBoardingWirePortalCutoff')
BEGIN
	ALTER TABLE onBoardingWirePortalCutoff ADD CutOffTimeZone VARCHAR(20) NOT NULL DEFAULT 'EST'
END
GO

IF NOT EXISTS(SELECT 8 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'RecCreatedBy' AND TABLE_NAME = 'onBoardingWirePortalCutoff')
BEGIN
	ALTER TABLE onBoardingWirePortalCutoff ADD RecCreatedBy INT NOT NULL DEFAULT 0
END
GO

IF NOT EXISTS(SELECT 8 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'RecCreatedAt' AND TABLE_NAME = 'onBoardingWirePortalCutoff')
BEGIN
	ALTER TABLE onBoardingWirePortalCutoff ADD RecCreatedAt DATETIME NOT NULL DEFAULT GETDATE()
END
GO
