IF NOT EXISTS(SELECT 8 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'CutOffTimeZone' AND TABLE_NAME = 'onBoardingAccount')
BEGIN
	ALTER TABLE onBoardingAccount ADD CutOffTimeZone VARCHAR(20) NOT NULL DEFAULT 'EST'
END
GO