//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HedgeMark.Operations.Secure.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class dmaAgreementOnBoardingAttribute
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dmaAgreementOnBoardingAttribute()
        {
            this.dmaAgreementOnBoardingChecklists = new HashSet<dmaAgreementOnBoardingChecklist>();
        }
    
        public long dmaAgreementOnBoardingAttributeId { get; set; }
        public string AttributeName { get; set; }
        public long dmaAttributeTypeId { get; set; }
        public string AgreementType { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsHMOps { get; set; }
        public int SortOrder { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dmaAgreementOnBoardingChecklist> dmaAgreementOnBoardingChecklists { get; set; }
    }
}
