//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HedgeMark.Operations.Secure.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class dmaAgreementOnBoarding
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dmaAgreementOnBoarding()
        {
            this.dmaAgreementDocuments = new HashSet<dmaAgreementDocument>();
            this.dmaAgreementSettlementInstructions = new HashSet<dmaAgreementSettlementInstruction>();
            this.dmaAgreementOnBoardingChecklists = new HashSet<dmaAgreementOnBoardingChecklist>();
        }
    
        public long dmaAgreementOnBoardingId { get; set; }
        public long dmaClientOnBoardId { get; set; }
        public Nullable<long> dmaCounterPartyOnBoardId { get; set; }
        public long dmaFundOnBoardId { get; set; }
        public string Priority { get; set; }
        public string Notes { get; set; }
        public string HistoricalNotes { get; set; }
        public string CounterpartyContact { get; set; }
        public string TemplateUsed { get; set; }
        public Nullable<System.DateTime> DateOfAgreement { get; set; }
        public Nullable<System.DateTime> FullyExecutedDate { get; set; }
        public Nullable<int> AgreementTypeId { get; set; }
        public Nullable<int> AgreementStatusId { get; set; }
        public Nullable<System.DateTime> NotesModifiedDate { get; set; }
        public string CounterPartyLegalEntity { get; set; }
        public string CPJurisdiction { get; set; }
        public string Comments { get; set; }
        public string NAVDeclineTest { get; set; }
        public string NAVDeclineTrigger1Month { get; set; }
        public string NAVDeclineTrigger3Month { get; set; }
        public string NAVDeclineTrigger12Month { get; set; }
        public string NAVDeclineTriggerOthers { get; set; }
        public string NAVFloor1 { get; set; }
        public string NAVFloor2 { get; set; }
        public string LegalEntityNameAdminAccount { get; set; }
        public string ReportingRequired { get; set; }
        public string ReportingRequiredNotes { get; set; }
        public string EmailAddress { get; set; }
        public string TimeingFinalNAV { get; set; }
        public string EstimatedNAV { get; set; }
        public string AuditedFinancial { get; set; }
        public string AgreementTask { get; set; }
        public Nullable<int> TimingFinalNAVDays { get; set; }
        public Nullable<int> UponRequestDays { get; set; }
        public string UponRequest { get; set; }
        public Nullable<int> AfterMonthEndDays { get; set; }
        public string AfterMonthEnd { get; set; }
        public Nullable<int> AuditedFinancialDays { get; set; }
        public string AuditedFinancialOption { get; set; }
        public Nullable<int> NAVDeclineTrigger1MonthPercentage { get; set; }
        public Nullable<int> NAVDeclineTrigger3MonthPercentage { get; set; }
        public Nullable<int> NAVDeclineTrigger12MonthPercentage { get; set; }
        public Nullable<int> NAVDeclineTriggerOthersPercentage { get; set; }
        public string NAVFloor1Dollarvalue { get; set; }
        public Nullable<int> NAVFloor1HistoricPercentage { get; set; }
        public string NAVFloor2Dollarvalue { get; set; }
        public Nullable<int> NAVFloor2HistoricPercentage { get; set; }
        public bool IsDeleted { get; set; }
        public string AgreementLongName { get; set; }
        public string AgreementShortName { get; set; }
        public Nullable<long> dmaCounterPartyFamilyId { get; set; }
        public string GoverningLaw { get; set; }
        public string TargetCompletion { get; set; }
        public Nullable<int> RelativeDays { get; set; }
        public string RelativeOptions { get; set; }
        public string CurrencyCode { get; set; }
        public string PostingParty { get; set; }
        public Nullable<double> DeliveryAmount { get; set; }
        public Nullable<double> ReturnAmount { get; set; }
        public string CreditSupportAmount { get; set; }
        public string ThresholdIATerms { get; set; }
        public Nullable<double> ThresholdwrtFund { get; set; }
        public Nullable<double> ThresholdwrtCounterparty { get; set; }
        public Nullable<double> MTAwrtFund { get; set; }
        public Nullable<double> MTAwrtCounterparty { get; set; }
        public Nullable<double> DeliverRoundingAmount { get; set; }
        public string DeliverRoundingMethod { get; set; }
        public Nullable<double> ReturnRoundingAmount { get; set; }
        public string ReturnRoundingMethod { get; set; }
        public string ThresholdIATermsforMTM { get; set; }
        public Nullable<double> ThresholdwrtFundforMTM { get; set; }
        public Nullable<double> ThresholdwrtCounterpartyforMTM { get; set; }
        public Nullable<double> MTAwrtFundforMTM { get; set; }
        public Nullable<double> MTAwrtCounterpartyforMTM { get; set; }
        public Nullable<double> DeliverRoundingAmountforMTM { get; set; }
        public string DeliverRoundingMethodforMTM { get; set; }
        public Nullable<double> ReturnRoundingAmountforMTM { get; set; }
        public string ReturnRoundingMethodforMTM { get; set; }
        public string ValuationAgent { get; set; }
        public string ValuationAgentInfo { get; set; }
        public Nullable<System.TimeSpan> NotificationTime { get; set; }
        public string NotificationTimeZone { get; set; }
        public string TransferTiming { get; set; }
        public bool RehypothecationPermittedByFund { get; set; }
        public bool RehypothecationPermittedByCounterparty { get; set; }
        public bool SegregationRequiredByFund { get; set; }
        public bool SegregationRequiredByCounterparty { get; set; }
        public string InterestRateSource { get; set; }
        public Nullable<double> InterestRateSpread { get; set; }
        public bool NegativeInterestAllowed { get; set; }
        public string TransferOfInterest { get; set; }
        public string AdditionalCollateralNotes { get; set; }
        public string RECON_THRESHOLD_CURRENCY_CODE { get; set; }
        public Nullable<double> RECON_THRESHOLD { get; set; }
        public string MTA_CURRENCY_CODE { get; set; }
        public Nullable<double> MTA_THRESHOLD { get; set; }
        public string ROUNDING_TYPE { get; set; }
        public string ROUNDING_CURRENCY_CODE { get; set; }
        public Nullable<double> ROUNDING_TOLERANCE { get; set; }
        public string NOTIFICATION_DEADLINE { get; set; }
        public string MARGIN_DELIVERY_DEADLINE { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string HMOpsStatus { get; set; }
        public Nullable<long> dmaOnBoardingAgreementVersionId { get; set; }
        public string HMTemplate { get; set; }
        public Nullable<System.DateTime> TargetCompletionDate { get; set; }
        public bool PBFXNetting { get; set; }
        public bool DataBackfill { get; set; }
        public Nullable<System.DateTime> StatusDate { get; set; }
        public string NAVFloor1DollarValueComparison { get; set; }
        public string NAVFloor1HistoricPercentageComparison { get; set; }
        public string NAVFloor2DollarValueComparison { get; set; }
        public string NAVFloor2HistoricPercentageComparison { get; set; }
        public string ExpiringNAVFloor { get; set; }
        public string ExpiringNAVFloorDollarvalue { get; set; }
        public string ExpiringNAVFloorHistoricPercentage { get; set; }
        public Nullable<int> ExpiringNAVFloorDollarvalueYearEnds { get; set; }
        public Nullable<int> ExpiringNAVFloorDollarvalueofMonths { get; set; }
        public Nullable<int> ExpiringNAVFloorHistoricPercentageYearEnds { get; set; }
        public Nullable<int> ExpiringNAVFloorHistoricPercentageofMonths { get; set; }
        public string ExpiringDate { get; set; }
        public Nullable<int> FromAgreementDateMonth { get; set; }
        public Nullable<int> FromLaunchMonth { get; set; }
        public Nullable<System.DateTime> FixedExpirationDate { get; set; }
        public string NAVAdditionalComments { get; set; }
        public string InterestMethod { get; set; }
        public Nullable<bool> IsRepoCollateral { get; set; }
        public Nullable<bool> LegalOrOperational { get; set; }
        public string keymanContact { get; set; }
        public string ProcessAgent { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dmaAgreementDocument> dmaAgreementDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dmaAgreementSettlementInstruction> dmaAgreementSettlementInstructions { get; set; }
        public virtual dmaAgreementStatu dmaAgreementStatu { get; set; }
        public virtual dmaAgreementType dmaAgreementType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dmaAgreementOnBoardingChecklist> dmaAgreementOnBoardingChecklists { get; set; }
        public virtual dmaCounterPartyOnBoarding dmaCounterPartyOnBoarding { get; set; }
        public virtual onboardingFund onboardingFund { get; set; }
        public virtual dmaCounterpartyFamily dmaCounterpartyFamily { get; set; }
        public virtual onboardingClient onboardingClient { get; set; }
    }
}
