//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HedgeMark.Operations.Secure.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class dmaAgreementOnBoardingChecklist
    {
        public long dmaAgreementOnBoardingChecklistId { get; set; }
        public long dmaAgreementOnBoardingId { get; set; }
        public long dmaAgreementOnBoardingAttributeId { get; set; }
        public string Responsibility { get; set; }
        public string Status { get; set; }
        public string Comments { get; set; }
        public string ResponsibleParty { get; set; }
        public int DayCount { get; set; }
    
        public virtual dmaAgreementOnBoarding dmaAgreementOnBoarding { get; set; }
        public virtual dmaAgreementOnBoardingAttribute dmaAgreementOnBoardingAttribute { get; set; }
    }
}
