//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HedgeMark.Operations.Secure.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class dmaAgreementSettlementInstruction
    {
        public int dmaAgreementSettlementInstructionID { get; set; }
        public long dmaAgreementOnBoardingId { get; set; }
        public string SETTLEMENT_NAME { get; set; }
        public string BANK_NAME { get; set; }
        public string BANK_NUMBER { get; set; }
        public string ACCT_NAME { get; set; }
        public string ACCT_NUMBER { get; set; }
        public string FFC_NAME { get; set; }
        public string FFC_NUMBER { get; set; }
        public Nullable<int> SETTLEMENT_TYPE { get; set; }
    
        public virtual dmaAgreementOnBoarding dmaAgreementOnBoarding { get; set; }
    }
}
