//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HedgeMark.Operations.Secure.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class dmaCounterPartyOnBoarding
    {
        public long dmaCounterPartyOnBoardId { get; set; }
        public string CounterpartyShortCode { get; set; }
        public string CounterpartyName { get; set; }
        public Nullable<long> dmaCounterpartyFamilyId { get; set; }
        public bool IsDeleted { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    
        public virtual dmaCounterpartyFamily dmaCounterpartyFamily { get; set; }
    }
}
