//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HedgeMark.Operations.Secure.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class dmaCounterpartyFamily
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dmaCounterpartyFamily()
        {
            this.dmaCounterPartyOnBoardings = new HashSet<dmaCounterPartyOnBoarding>();
        }
    
        public long dmaCounterpartyFamilyId { get; set; }
        public string CounterpartyFamily { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dmaCounterPartyOnBoarding> dmaCounterPartyOnBoardings { get; set; }
    }
}
