//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HedgeMark.Operations.Secure.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class dmaInvoiceReport
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dmaInvoiceReport()
        {
            this.dmaInvoiceFileAttachments = new HashSet<dmaInvoiceFileAttachment>();
        }
    
        public long dmaInvoiceReportId { get; set; }
        public long dmaReportMapId { get; set; }
        public Nullable<long> dmaFileIdentifierId { get; set; }
        public long hFundId { get; set; }
        public int dmaInvoiceFeeTypeId { get; set; }
        public System.DateTime OriginalContextMonth { get; set; }
        public System.DateTime ContextMonth { get; set; }
        public string InvoiceNo { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public string Vendor { get; set; }
        public string Allocation { get; set; }
        public double Amount { get; set; }
        public Nullable<System.DateTime> PayDate { get; set; }
        public string Comments { get; set; }
        public bool IsClientApproved { get; set; }
        public bool IsNavCheckApproved { get; set; }
        public bool IsApproved { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedAt { get; set; }
        public bool IsDeleted { get; set; }
        public string LastModifiedBy { get; set; }
        public System.DateTime LastModifiedAt { get; set; }
        public double AppliedAmount { get; set; }
        public bool IsAppliedAmountEdited { get; set; }
        public Nullable<System.DateTime> ServicesCoveredFrom { get; set; }
        public Nullable<System.DateTime> ServicesCoveredTo { get; set; }
        public long VendorId { get; set; }
        public string Currency { get; set; }
        public string InvoiceDateComments { get; set; }
        public string Movement { get; set; }
        public string DuplicateInvoiceReason { get; set; }
        public bool SendToClientPortalForApproval { get; set; }
        public int ClientApprovalCode { get; set; }
        public Nullable<System.DateTime> ClientStatusUpdatedAt { get; set; }
        public string ClientApprovalRejectedReason { get; set; }
        public Nullable<int> ClientApprovalRequestedBy { get; set; }
        public Nullable<int> ClientStatusUpdatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dmaInvoiceFileAttachment> dmaInvoiceFileAttachments { get; set; }
    }
}
