//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HedgeMark.Operations.Secure.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class dmaReport
    {
        public long dmaReportsId { get; set; }
        public string ReportName { get; set; }
        public int DisplayOrder { get; set; }
        public bool IsFundPrimaryReport { get; set; }
    }
}
