//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HedgeMark.Operations.Secure.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class hmsAccountCallback
    {
        public long hmsAccountCallbackId { get; set; }
        public long onBoardingAccountId { get; set; }
        public string ContactName { get; set; }
        public string ContactNumber { get; set; }
        public string Title { get; set; }
        public bool IsCallbackConfirmed { get; set; }
        public string RecCreatedBy { get; set; }
        public System.DateTime RecCreatedDt { get; set; }
        public string ConfirmedBy { get; set; }
        public Nullable<System.DateTime> ConfirmedAt { get; set; }
    
        public virtual onBoardingAccount onBoardingAccount { get; set; }
    }
}
