//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HedgeMark.Operations.Secure.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class hmsDashboardTemplate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hmsDashboardTemplate()
        {
            this.hmsDashboardPreferences = new HashSet<hmsDashboardPreference>();
            this.hmsDashboardSchedules = new HashSet<hmsDashboardSchedule>();
        }
    
        public long hmsDashboardTemplateId { get; set; }
        public string TemplateName { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime RecCreatedDt { get; set; }
        public int RecCreatedById { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hmsDashboardPreference> hmsDashboardPreferences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hmsDashboardSchedule> hmsDashboardSchedules { get; set; }
    }
}
