//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HedgeMark.Operations.Secure.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class hmsInBoundMQLog
    {
        public long hmsInBoundMQLogsId { get; set; }
        public string InBoundMessage { get; set; }
        public System.DateTime CreatedAt { get; set; }
    }
}
