//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HedgeMark.Operations.Secure.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class hmsMQLog
    {
        public long hmsMQLogsId { get; set; }
        public bool IsOutBound { get; set; }
        public string QueueManager { get; set; }
        public string QueueName { get; set; }
        public string Message { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string OpsSecureHandlerMessage { get; set; }
    }
}
