//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HedgeMark.Operations.Secure.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class hmsUser
    {
        public long hmsWireUserId { get; set; }
        public int hmLoginId { get; set; }
        public string LdapRole { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public int CreatedBy { get; set; }
        public bool IsApproved { get; set; }
        public Nullable<System.DateTime> ApprovedAt { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public string AccountStatus { get; set; }
    }
}
