//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HedgeMark.Operations.Secure.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class hmsWirePortalCutoff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hmsWirePortalCutoff()
        {
            this.onBoardingAccounts = new HashSet<onBoardingAccount>();
        }
    
        public long hmsWirePortalCutoffId { get; set; }
        public string CashInstruction { get; set; }
        public string Country { get; set; }
        public string Currency { get; set; }
        public System.TimeSpan CutoffTime { get; set; }
        public int DaystoWire { get; set; }
        public string CutOffTimeZone { get; set; }
        public int RecCreatedBy { get; set; }
        public System.DateTime RecCreatedAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<onBoardingAccount> onBoardingAccounts { get; set; }
    }
}
