//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HedgeMark.Operations.Secure.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class hmsWireWorkflowLog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hmsWireWorkflowLog()
        {
            this.hmsWireLogs = new HashSet<hmsWireLog>();
        }
    
        public long hmsWireWorkflowLogId { get; set; }
        public long hmsWireId { get; set; }
        public int WireStatusId { get; set; }
        public string Comment { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public int CreatedBy { get; set; }
        public int SwiftStatusId { get; set; }
    
        public virtual hmsSwiftStatusLkup hmsSwiftStatusLkup { get; set; }
        public virtual hmsWireStatusLkup hmsWireStatusLkup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hmsWireLog> hmsWireLogs { get; set; }
        public virtual hmsWire hmsWire { get; set; }
    }
}
