//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HedgeMark.Operations.Secure.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class hmsWireLog
    {
        public long hmsWireLogId { get; set; }
        public long hmsWireId { get; set; }
        public int WireStatusId { get; set; }
        public int WireMessageTypeId { get; set; }
        public string OutBoundSwiftMessage { get; set; }
        public string ServiceSwiftMessage { get; set; }
        public string InBoundSwiftMessage { get; set; }
        public string ConfirmationMessageDetails { get; set; }
        public string ExceptionDetails { get; set; }
        public System.DateTime RecCreatedAt { get; set; }
        public bool IsFrontEndAcknowleged { get; set; }
    
        public virtual hmsWireMessageType hmsWireMessageType { get; set; }
        public virtual hmsWireStatusLkup hmsWireStatusLkup { get; set; }
        public virtual hmsWire hmsWire { get; set; }
    }
}
