//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HedgeMark.Operations.Secure.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class onBoardingAccountBICorABA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public onBoardingAccountBICorABA()
        {
            this.onBoardingSSITemplates = new HashSet<onBoardingSSITemplate>();
            this.onBoardingSSITemplates1 = new HashSet<onBoardingSSITemplate>();
            this.onBoardingSSITemplates2 = new HashSet<onBoardingSSITemplate>();
            this.onBoardingAccounts = new HashSet<onBoardingAccount>();
            this.onBoardingAccounts1 = new HashSet<onBoardingAccount>();
            this.onBoardingAccounts2 = new HashSet<onBoardingAccount>();
        }
    
        public long onBoardingAccountBICorABAId { get; set; }
        public string BICorABA { get; set; }
        public string BankName { get; set; }
        public bool IsABA { get; set; }
        public string BankAddress { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public bool IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<onBoardingSSITemplate> onBoardingSSITemplates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<onBoardingSSITemplate> onBoardingSSITemplates1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<onBoardingSSITemplate> onBoardingSSITemplates2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<onBoardingAccount> onBoardingAccounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<onBoardingAccount> onBoardingAccounts1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<onBoardingAccount> onBoardingAccounts2 { get; set; }
    }
}
