//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HedgeMark.Operations.Secure.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnBoardingSSITemplateServiceProvider
    {
        public long OnBoardingSSITemplateServiceProviderId { get; set; }
        public string Reason { get; set; }
        public string ServiceProvider { get; set; }
    }
}
