//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HedgeMark.Operations.Secure.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnBoardingServiceProvider
    {
        public long OnBoardingServiceProviderId { get; set; }
        public string FeeType { get; set; }
        public string ServiceProvider { get; set; }
    }
}
