//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HedgeMark.Operations.Secure.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class onBoardingAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public onBoardingAccount()
        {
            this.onBoardingAccountDocuments = new HashSet<onBoardingAccountDocument>();
            this.onBoardingAccountSSITemplateMaps = new HashSet<onBoardingAccountSSITemplateMap>();
            this.onBoardingAccountModuleAssociations = new HashSet<onBoardingAccountModuleAssociation>();
        }
    
        public long onBoardingAccountId { get; set; }
        public long dmaFundOnBoardId { get; set; }
        public Nullable<long> dmaAgreementOnBoardingId { get; set; }
        public string AccountName { get; set; }
        public string AccountNumber { get; set; }
        public string BeneficiaryType { get; set; }
        public string BeneficiaryBICorABA { get; set; }
        public string BeneficiaryBankName { get; set; }
        public string BeneficiaryBankAddress { get; set; }
        public string BeneficiaryAccountNumber { get; set; }
        public string IntermediaryType { get; set; }
        public string IntermediaryBICorABA { get; set; }
        public string IntermediaryBankName { get; set; }
        public string IntermediaryBankAddress { get; set; }
        public string IntermediaryAccountNumber { get; set; }
        public string UltimateBeneficiaryType { get; set; }
        public string UltimateBeneficiaryBICorABA { get; set; }
        public string UltimateBeneficiaryBankName { get; set; }
        public string UltimateBeneficiaryBankAddress { get; set; }
        public string FFCName { get; set; }
        public string FFCNumber { get; set; }
        public string Reference { get; set; }
        public string Currency { get; set; }
        public string Description { get; set; }
        public string Notes { get; set; }
        public string AuthorizedParty { get; set; }
        public string CashInstruction { get; set; }
        public string CashSweep { get; set; }
        public Nullable<System.TimeSpan> CashSweepTime { get; set; }
        public string CashSweepTimeZone { get; set; }
        public string ContactType { get; set; }
        public string ContactName { get; set; }
        public string ContactNumber { get; set; }
        public string ContactEmail { get; set; }
        public string onBoardingAccountStatus { get; set; }
        public string StatusComments { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.TimeSpan> CutoffTime { get; set; }
        public string AccountType { get; set; }
        public Nullable<long> BrokerId { get; set; }
        public Nullable<int> DaystoWire { get; set; }
        public string SwiftGroup { get; set; }
        public string SendersBIC { get; set; }
        public string AccountPurpose { get; set; }
        public string AccountStatus { get; set; }
        public Nullable<double> HoldbackAmount { get; set; }
        public string SweepComments { get; set; }
        public string AssociatedCustodyAcct { get; set; }
        public string PortfolioSelection { get; set; }
        public string TickerorISIN { get; set; }
        public string SweepCurrency { get; set; }
        public string UltimateBeneficiaryAccountName { get; set; }
        public string AccountModule { get; set; }
        public string ApprovedBy { get; set; }
        public string CutOffTimeZone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<onBoardingAccountDocument> onBoardingAccountDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<onBoardingAccountSSITemplateMap> onBoardingAccountSSITemplateMaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<onBoardingAccountModuleAssociation> onBoardingAccountModuleAssociations { get; set; }
    }
}
