//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HedgeMark.Operations.Secure.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class onBoardingAccountModuleAssociation
    {
        public long onBoardingAccountModuleAssociationId { get; set; }
        public long onBoardingAccountId { get; set; }
        public long onBoardingModuleId { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual onBoardingAccount onBoardingAccount { get; set; }
        public virtual onBoardingModule onBoardingModule { get; set; }
    }
}
