//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HedgeMark.Operations.Secure.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OperationsSecureContext : DbContext
    {
        public OperationsSecureContext()
            : base("name=OperationsSecureContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<hmsWireDocument> hmsWireDocuments { get; set; }
        public virtual DbSet<hmsWireMessageType> hmsWireMessageTypes { get; set; }
        public virtual DbSet<hmsWireStatusLkup> hmsWireStatusLkups { get; set; }
        public virtual DbSet<hmsSwiftStatusLkup> hmsSwiftStatusLkups { get; set; }
        public virtual DbSet<hmsWireWorkflowLog> hmsWireWorkflowLogs { get; set; }
        public virtual DbSet<hmsWireJobSchedule> hmsWireJobSchedules { get; set; }
        public virtual DbSet<hmsNotificationStaging> hmsNotificationStagings { get; set; }
        public virtual DbSet<hmsWirePurposeLkup> hmsWirePurposeLkups { get; set; }
        public virtual DbSet<hmsWireTransferTypeLKup> hmsWireTransferTypeLKups { get; set; }
        public virtual DbSet<hmsMQLog> hmsMQLogs { get; set; }
        public virtual DbSet<hmsWireLog> hmsWireLogs { get; set; }
        public virtual DbSet<hmsWireLogTypeLkup> hmsWireLogTypeLkups { get; set; }
        public virtual DbSet<hmsUserAuditLog> hmsUserAuditLogs { get; set; }
        public virtual DbSet<onBoardingAccountBICorABA> onBoardingAccountBICorABAs { get; set; }
        public virtual DbSet<OnBoardingAccountDescription> OnBoardingAccountDescriptions { get; set; }
        public virtual DbSet<onBoardingAccountDocument> onBoardingAccountDocuments { get; set; }
        public virtual DbSet<onBoardingAccountSSITemplateMap> onBoardingAccountSSITemplateMaps { get; set; }
        public virtual DbSet<onBoardingAuthorizedParty> onBoardingAuthorizedParties { get; set; }
        public virtual DbSet<onBoardingCashInstruction> onBoardingCashInstructions { get; set; }
        public virtual DbSet<OnBoardingSSITemplateAccountType> OnBoardingSSITemplateAccountTypes { get; set; }
        public virtual DbSet<onBoardingSSITemplateDocument> onBoardingSSITemplateDocuments { get; set; }
        public virtual DbSet<hmsWireSenderInformation> hmsWireSenderInformations { get; set; }
        public virtual DbSet<onBoardingAccountModuleAssociation> onBoardingAccountModuleAssociations { get; set; }
        public virtual DbSet<onBoardingModule> onBoardingModules { get; set; }
        public virtual DbSet<hmsWireInvoiceAssociation> hmsWireInvoiceAssociations { get; set; }
        public virtual DbSet<hmsWireCollateralAssociation> hmsWireCollateralAssociations { get; set; }
        public virtual DbSet<hmsBulkUploadLog> hmsBulkUploadLogs { get; set; }
        public virtual DbSet<hmsWireCutoffTimeZone> hmsWireCutoffTimeZones { get; set; }
        public virtual DbSet<hmsSystemPreference> hmsSystemPreferences { get; set; }
        public virtual DbSet<hmsActionInProgress> hmsActionInProgresses { get; set; }
        public virtual DbSet<hmsSwiftGroupStatusLkp> hmsSwiftGroupStatusLkps { get; set; }
        public virtual DbSet<onBoardingSSITemplate> onBoardingSSITemplates { get; set; }
        public virtual DbSet<hmsAccountCallback> hmsAccountCallbacks { get; set; }
        public virtual DbSet<hmsSwiftGroup> hmsSwiftGroups { get; set; }
        public virtual DbSet<hmsCurrency> hmsCurrencies { get; set; }
        public virtual DbSet<vw_FundAccounts> vw_FundAccounts { get; set; }
        public virtual DbSet<hmsSSICallback> hmsSSICallbacks { get; set; }
        public virtual DbSet<hmsWire> hmsWires { get; set; }
        public virtual DbSet<onBoardingAccount> onBoardingAccounts { get; set; }
        public virtual DbSet<hmsCollateralCashPurposeLkup> hmsCollateralCashPurposeLkups { get; set; }
        public virtual DbSet<hmsWireField> hmsWireFields { get; set; }
        public virtual DbSet<hmsWirePortalCutoff> hmsWirePortalCutoffs { get; set; }
        public virtual DbSet<hmsDashboardPreferenceCodeLkup> hmsDashboardPreferenceCodeLkups { get; set; }
        public virtual DbSet<hmsDashboardPreference> hmsDashboardPreferences { get; set; }
        public virtual DbSet<hmsDashboardScheduleRangeLkup> hmsDashboardScheduleRangeLkups { get; set; }
        public virtual DbSet<hmsDashboardSchedule> hmsDashboardSchedules { get; set; }
        public virtual DbSet<hmsDashboardTemplate> hmsDashboardTemplates { get; set; }
        public virtual DbSet<hmsScheduleLog> hmsScheduleLogs { get; set; }
        public virtual DbSet<hmsSchedule> hmsSchedules { get; set; }
        public virtual DbSet<hmsScheduleWorkflowLkup> hmsScheduleWorkflowLkups { get; set; }
        public virtual DbSet<hmsUser> hmsUsers { get; set; }
    }
}
