//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HedgeMark.Operations.Secure.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_dmaInvoiceReport
    {
        public long dmaInvoiceReportId { get; set; }
        public string LegalFundName { get; set; }
        public string ClientFundName { get; set; }
        public string ShortFundName { get; set; }
        public string FeeType { get; set; }
        public string FileName { get; set; }
        public string Vendor { get; set; }
        public string FileSource { get; set; }
        public string InvoiceNo { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public Nullable<System.DateTime> ServicesCoveredFrom { get; set; }
        public Nullable<System.DateTime> ServicesCoveredTo { get; set; }
        public double Amount { get; set; }
        public Nullable<System.DateTime> PaidDate { get; set; }
        public bool ClientApproval { get; set; }
        public string Currency { get; set; }
        public string ClientApprovalStatus { get; set; }
        public string ApprovedBy { get; set; }
        public System.DateTime InvoiceCreatedTimestamp { get; set; }
        public Nullable<System.DateTime> ApprovedTimestamp { get; set; }
        public Nullable<int> Child { get; set; }
        public System.DateTime OriginalContextMonth { get; set; }
        public bool SendToClientPortalForApproval { get; set; }
    }
}
