//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HedgeMark.Operations.Secure.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_HFund
    {
        public int hmFundId { get; set; }
        public string ShortFundName { get; set; }
        public string LegalFundName { get; set; }
        public string HMRAName { get; set; }
        public string FundType { get; set; }
        public string FundStatus { get; set; }
        public Nullable<int> DataProviderNameId { get; set; }
        public string DataProviderName { get; set; }
        public string varPositionFrequency { get; set; }
        public string NAVFrequency { get; set; }
        public string FundLegalStructure { get; set; }
        public string BaseCurrencyShareclass { get; set; }
        public string AccountingMethod { get; set; }
        public string FiscalYearEnd { get; set; }
        public string FundManagerName { get; set; }
        public Nullable<int> FundManagerID { get; set; }
        public Nullable<long> dmaFundOnBoardId { get; set; }
        public Nullable<long> dmaClientOnBoardId { get; set; }
        public Nullable<System.DateTime> ActualLaunchDate { get; set; }
        public Nullable<System.DateTime> TradeStartDate { get; set; }
        public Nullable<long> AdminChoiceId { get; set; }
        public string AdminChoice { get; set; }
        public Nullable<long> FundStructureId { get; set; }
    }
}
