//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HedgeMark.Operations.Secure.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_HFund
    {
        public int intFundID { get; set; }
        public int FundMapId { get; set; }
        public string varFundLongName { get; set; }
        public string varFundShortName { get; set; }
        public string varMRDBName { get; set; }
        public string varPositionFrequency { get; set; }
        public string FiscalYearEnd { get; set; }
        public string varCurrencyISO { get; set; }
        public string subFunds { get; set; }
        public string CreatedFor { get; set; }
        public string FundStatus { get; set; }
        public Nullable<int> DataProviderNameId { get; set; }
        public string DataProviderName { get; set; }
    }
}
