//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HedgeMark.Operations.Secure.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ProxyCurrencyConversionData
    {
        public long HM_SECURITY_ID { get; set; }
        public Nullable<System.DateTime> HM_CONTEXT_DT { get; set; }
        public string FROM_CRNCY { get; set; }
        public string TO_CRNCY { get; set; }
        public Nullable<decimal> FX_RATE { get; set; }
    }
}
