//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HM.Operations.Secure.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class dmaCollateralData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dmaCollateralData()
        {
            this.dmaOpsCashCollaterals = new HashSet<dmaOpsCashCollateral>();
        }
    
        public long dmaCollateralDataId { get; set; }
        public System.DateTime ContextDate { get; set; }
        public string BrokerName { get; set; }
        public string CallStatus { get; set; }
        public string CallSubStatus { get; set; }
        public Nullable<double> CollateralPledgedToByFundVerifiedBalance { get; set; }
        public Nullable<double> ExposureOrMtm { get; set; }
        public double AdditionalIaOrFxnop { get; set; }
        public Nullable<double> CollateralCallFromBroker { get; set; }
        public Nullable<double> AgreedMovementToFromFund { get; set; }
        public double EndingTotalCollateralBalance { get; set; }
        public bool overrideCollateralBalanceFlag { get; set; }
        public Nullable<double> CollateralDueToFromFund { get; set; }
        public Nullable<double> IndependentAmount { get; set; }
        public string DataCallStatus { get; set; }
        public Nullable<double> CollateralPledgedToByFundCounterpartyStatement { get; set; }
        public Nullable<int> DisputeAging { get; set; }
        public Nullable<double> EndingCollateralPledgedToOrByFund { get; set; }
        public Nullable<double> MTMDiscrepancy { get; set; }
        public string CollateralComment { get; set; }
        public Nullable<double> CollateralPledgedToByFundSystemBalance { get; set; }
        public Nullable<double> BeginningTotalCollatBalanceSettledPlusPending { get; set; }
        public Nullable<System.TimeSpan> CallDeadline { get; set; }
        public Nullable<double> CollateralCallFromFund { get; set; }
        public string CollateralDirection { get; set; }
        public Nullable<double> CollateralPendingToFromFund { get; set; }
        public Nullable<double> CollateralPledgedToByFundAdminBalance { get; set; }
        public Nullable<double> CreditSupportAmount { get; set; }
        public Nullable<double> DeliverRoundingAmount { get; set; }
        public string DeliverRoundingMethod { get; set; }
        public Nullable<double> DiffVsAdminFile { get; set; }
        public Nullable<double> DiffVsBroker { get; set; }
        public Nullable<long> FileIdentifierId { get; set; }
        public Nullable<int> intFundId { get; set; }
        public string MarginTransferTiming { get; set; }
        public Nullable<double> MtaWithRespectToCounterparty { get; set; }
        public Nullable<double> MtaWithRespectToFund { get; set; }
        public Nullable<double> NetCollateralDueToFromFund { get; set; }
        public System.DateTime RecordCreatedDate { get; set; }
        public Nullable<long> ReportMapId { get; set; }
        public Nullable<double> ReturnRoundingAmount { get; set; }
        public string ReturnRoundingMethod { get; set; }
        public string RiskType { get; set; }
        public Nullable<double> Threshold { get; set; }
        public Nullable<double> ThresholdWithRespectToCounterparty { get; set; }
        public Nullable<double> ThresholdWithRespectToFund { get; set; }
        public Nullable<double> Tplus1CollateralMovementToFromFund { get; set; }
        public bool isLocked { get; set; }
        public bool IsCounterpartyStatementOverridden { get; set; }
        public bool IsCollateralCallFromBrokerOverridden { get; set; }
        public bool IsVerifiedBalanceOverridden { get; set; }
        public bool IsAdditionalIaOrFxnopOverridden { get; set; }
        public string Currency { get; set; }
        public bool IsCollateralFundCallSent { get; set; }
        public bool IsCollateralBrokerCallResponded { get; set; }
        public Nullable<long> dmaFundBrokerAgreementMapId { get; set; }
        public bool IsPBFXNettingEnabled { get; set; }
        public Nullable<double> PBFXNettingAmount { get; set; }
        public bool IsAgreedMovementToFromFundOverridden { get; set; }
        public Nullable<double> InterestPending { get; set; }
        public string RecCreatedBy { get; set; }
        public Nullable<bool> IsCompleted { get; set; }
        public Nullable<double> CollateralExposureOrMtm { get; set; }
        public string ReasonToAgree { get; set; }
        public Nullable<double> MTMDifference { get; set; }
        public Nullable<double> IADifference { get; set; }
        public double DeliverAmountToFromFund { get; set; }
        public double ReturnAmountToFromFund { get; set; }
        public bool IsDeliverAmountToFromFundOverridden { get; set; }
        public bool IsBrokerResponseConfirmed { get; set; }
        public bool IsCollateralCallFromFundOverridden { get; set; }
        public string BrokerStatus { get; set; }
        public bool IsReportStatusOverridden { get; set; }
        public string AcadiaCallStatus { get; set; }
        public bool IsPledgedCptyFileReceived { get; set; }
        public bool IsCollateralReport { get; set; }
        public Nullable<double> CounterpartyIA { get; set; }
        public Nullable<double> PendingCollateral { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dmaOpsCashCollateral> dmaOpsCashCollaterals { get; set; }
    }
}
