//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HM.Operations.Secure.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class dmaFundOnBoardPermission
    {
        public long dmaFundOnBoardPermissionsId { get; set; }
        public long dmaFundOnBoardId { get; set; }
        public int userId { get; set; }
        public int dmaPermissionLevelId { get; set; }
        public System.DateTime RecCreatedDt { get; set; }
        public string RecCreatedBy { get; set; }
    
        public virtual onboardingFund onboardingFund { get; set; }
    }
}
