//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HM.Operations.Secure.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class dmaInterestReportEodData
    {
        public long dmaInterestReportEodDataId { get; set; }
        public System.DateTime startDate { get; set; }
        public System.DateTime endDate { get; set; }
        public string brokerName { get; set; }
        public double hmInterestRateCalc { get; set; }
        public double counterpartyInterestRateCalc { get; set; }
        public Nullable<double> AgreedAmount { get; set; }
        public string SettlementOfInterest { get; set; }
        public System.DateTime ModifiedAt { get; set; }
        public Nullable<bool> isOverrideSettlementIntr { get; set; }
        public double hmInterestRateCalcIA { get; set; }
        public double counterpartyInterestRateCalcIA { get; set; }
        public Nullable<double> AgreedAmountIA { get; set; }
        public string SettlementOfInterestIA { get; set; }
        public bool IsOverrideCounterpartyIntr { get; set; }
        public bool IsOverrideCounterpartyIntrIA { get; set; }
        public Nullable<System.DateTime> InterestSettlementDate { get; set; }
        public Nullable<System.DateTime> InterestSettlementDateIA { get; set; }
        public string CompletedBy { get; set; }
        public Nullable<System.DateTime> CompletedAt { get; set; }
        public Nullable<long> AgreementId { get; set; }
        public string Status { get; set; }
        public Nullable<long> dmaReportMapId { get; set; }
        public string Currency { get; set; }
    }
}
