//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HM.Operations.Secure.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class dmaOpsCashCollateral
    {
        public long dmaOpsCashCollateralId { get; set; }
        public string EligibleCurrency { get; set; }
        public System.DateTime SettlementDate { get; set; }
        public string AgreedMovementType { get; set; }
        public Nullable<double> BaseCollateralValue { get; set; }
        public Nullable<double> CollateralValue { get; set; }
        public Nullable<double> PledgeAmount { get; set; }
        public Nullable<double> ReturnAmount { get; set; }
        public System.DateTime RecCreatedDate { get; set; }
        public string RecCreatedBy { get; set; }
        public bool IsPledgeCancelledOrRejected { get; set; }
        public bool IsBalanceOverriden { get; set; }
        public bool IsCurrencyPledged { get; set; }
        public Nullable<double> FXRate { get; set; }
        public Nullable<double> FXRateValue { get; set; }
        public Nullable<long> dmaCollateralDataId { get; set; }
    
        public virtual dmaCollateralData dmaCollateralData { get; set; }
    }
}
