//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HM.Operations.Secure.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class dmaTreasuryCashBalance
    {
        public long dmaTreasuryCashBalanceId { get; set; }
        public long onboardAccountId { get; set; }
        public string Currency { get; set; }
        public System.DateTime ContextDate { get; set; }
        public Nullable<decimal> CashBalance { get; set; }
        public Nullable<decimal> MinimunEquity { get; set; }
        public System.DateTime RecCreatedDt { get; set; }
        public string AccountOrAgreementType { get; set; }
        public Nullable<decimal> MarginBuffer { get; set; }
    }
}
