//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HM.Operations.Secure.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class hmsBulkUploadLog
    {
        public long hmsBulkUploadLogId { get; set; }
        public string FileName { get; set; }
        public bool IsFundAccountLog { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string UserName { get; set; }
    }
}
