//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HM.Operations.Secure.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class hmsDashboardSchedule
    {
        public int hmsDashboardScheduleId { get; set; }
        public int hmsScheduleId { get; set; }
        public long hmsDashboardTemplateId { get; set; }
        public int DashboardScheduleRangeLkupId { get; set; }
        public System.DateTime LastUpdatedAt { get; set; }
        public int LastModifiedBy { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual hmsDashboardScheduleRangeLkup hmsDashboardScheduleRangeLkup { get; set; }
        public virtual hmsDashboardTemplate hmsDashboardTemplate { get; set; }
        public virtual hmsSchedule hmsSchedule { get; set; }
    }
}
