//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HM.Operations.Secure.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class hmsDashboardPreference
    {
        public long hmsDashboardPreferenceId { get; set; }
        public long hmsDashboardTemplateId { get; set; }
        public int PreferenceCode { get; set; }
        public string Preferences { get; set; }
        public System.DateTime RecCreatedDt { get; set; }
        public int RecCreatedById { get; set; }
    
        public virtual hmsDashboardPreferenceCodeLkup hmsDashboardPreferenceCodeLkup { get; set; }
        public virtual hmsDashboardTemplate hmsDashboardTemplate { get; set; }
    }
}
