//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HM.Operations.Secure.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class hmsFundAccountClearingBroker
    {
        public long hmsFundAccountClearingBrokerId { get; set; }
        public long onBoardingAccountId { get; set; }
        public string MarginExposureType { get; set; }
        public System.DateTime RecCreatedAt { get; set; }
        public int RecCreatedById { get; set; }
        public string ClearingBrokerName { get; set; }
    
        public virtual onBoardingAccount onBoardingAccount { get; set; }
    }
}
