//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HM.Operations.Secure.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class hmsNotificationStaging
    {
        public long hmsNotificationStagingId { get; set; }
        public int FromUserId { get; set; }
        public int ToUserId { get; set; }
        public string Title { get; set; }
        public string Message { get; set; }
        public System.DateTime CreatedAt { get; set; }
    }
}
