//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HM.Operations.Secure.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class hmsSSIPaymentReasonForDescription
    {
        public int hmsSSIPaymentReasonForDescriptionId { get; set; }
        public int hmsSSIDescriptionId { get; set; }
        public string PaymentReason { get; set; }
        public string RecCreatedBy { get; set; }
        public System.DateTime RecCreatedDt { get; set; }
    
        public virtual hmsSSIDescription hmsSSIDescription { get; set; }
    }
}
