//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HM.Operations.Secure.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class hmsSchedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hmsSchedule()
        {
            this.hmsDashboardSchedules = new HashSet<hmsDashboardSchedule>();
            this.hmsScheduleLogs = new HashSet<hmsScheduleLog>();
        }
    
        public int hmsScheduleId { get; set; }
        public string Frequency { get; set; }
        public string ScheduleExpression { get; set; }
        public string TimeZone { get; set; }
        public string To { get; set; }
        public string CC { get; set; }
        public string ExternalTo { get; set; }
        public string ExternalToApproved { get; set; }
        public bool IsActive { get; set; }
        public string FileFormat { get; set; }
        public string SFTPFolder { get; set; }
        public string InternalFolder { get; set; }
        public string ReportFileName { get; set; }
        public int PreferredFundNameCode { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime LastUpdatedAt { get; set; }
        public int LastModifiedBy { get; set; }
        public int ExternalToWorkflowCode { get; set; }
        public Nullable<int> ExternalToModifiedBy { get; set; }
        public Nullable<System.DateTime> ExternalToModifiedAt { get; set; }
        public string ExternalToComments { get; set; }
        public int SFTPFolderWorkflowCode { get; set; }
        public Nullable<int> SFTPFolderModifiedBy { get; set; }
        public Nullable<System.DateTime> SFTPFolderModifiedAt { get; set; }
        public string SFTPFolderComments { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hmsDashboardSchedule> hmsDashboardSchedules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hmsScheduleLog> hmsScheduleLogs { get; set; }
    }
}
