//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HM.Operations.Secure.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class hmsScheduleLog
    {
        public int hmsScheduleLogId { get; set; }
        public int hmsScheduleId { get; set; }
        public System.DateTime ContextDate { get; set; }
        public System.DateTime ScheduleStartTime { get; set; }
        public Nullable<System.DateTime> ScheduleEndTime { get; set; }
        public string TimeOutJobId { get; set; }
        public System.DateTime RecCreatedAt { get; set; }
    
        public virtual hmsSchedule hmsSchedule { get; set; }
    }
}
