//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HM.Operations.Secure.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class hmsWireAutoCancellationJob
    {
        public long hmsWireJobSchedulerId { get; set; }
        public long hmsWireId { get; set; }
        public System.DateTime ScheduledDate { get; set; }
        public bool IsJobExecuted { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime LastModifiedAt { get; set; }
        public string JobId { get; set; }
    
        public virtual hmsWire hmsWire { get; set; }
    }
}
