//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HM.Operations.Secure.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class hmsWirePurposeControl
    {
        public int hmsWirePurposeControlId { get; set; }
        public int hmsWirePurposeId { get; set; }
        public int WireTransferTypeId { get; set; }
        public bool IsApproved { get; set; }
        public bool IsApprovalRequested { get; set; }
        public System.DateTime RecCreatedAt { get; set; }
        public int RecCreatedById { get; set; }
        public System.DateTime LastModifiedAt { get; set; }
        public int LastModifiedById { get; set; }
    
        public virtual hmsWirePurposeLkup hmsWirePurposeLkup { get; set; }
        public virtual hmsWireTransferTypeLKup hmsWireTransferTypeLKup { get; set; }
    }
}
