//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HM.Operations.Secure.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class hmsWireInvoiceAssociation
    {
        public long hmsWireInvoiceAssociationId { get; set; }
        public long hmsWireId { get; set; }
        public long InvoiceId { get; set; }
    
        public virtual hmsWire hmsWire { get; set; }
    }
}
