//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HM.Operations.Secure.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnBoardingServiceProvider
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OnBoardingServiceProvider()
        {
            this.OnBoardingFundServiceProviderMaps = new HashSet<OnBoardingFundServiceProviderMap>();
        }
    
        public long OnBoardingServiceProviderId { get; set; }
        public string FeeType { get; set; }
        public string ServiceProvider { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OnBoardingFundServiceProviderMap> OnBoardingFundServiceProviderMaps { get; set; }
    }
}
