//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HM.Operations.Secure.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class onBoardingSSITemplateDocument
    {
        public long onBoardingSSITemplateDocumentId { get; set; }
        public long onBoardingSSITemplateId { get; set; }
        public string FileName { get; set; }
        public string RecCreatedBy { get; set; }
        public Nullable<System.DateTime> RecCreatedAt { get; set; }
    
        public virtual onBoardingSSITemplate onBoardingSSITemplate { get; set; }
    }
}
