//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HM.Operations.Secure.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnBoardingSSITemplateAccountType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OnBoardingSSITemplateAccountType()
        {
            this.onBoardingSSITemplates = new HashSet<onBoardingSSITemplate>();
        }
    
        public long OnBoardingSSITemplateAccountTypeId { get; set; }
        public string Reason { get; set; }
        public int dmaAgreementTypeId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<onBoardingSSITemplate> onBoardingSSITemplates { get; set; }
    }
}
