//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HM.Operations.Secure.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class onboardingContactFundMap
    {
        public long onboardingContactFundMapId { get; set; }
        public long dmaOnBoardingContactDetailId { get; set; }
        public long dmaFundOnBoardId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual dmaOnBoardingContactDetail dmaOnBoardingContactDetail { get; set; }
        public virtual onboardingFund onboardingFund { get; set; }
    }
}
