//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HM.Operations.Secure.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_FundAgreementDetails
    {
        public long RowId { get; set; }
        public Nullable<long> dmaAgreementOnBoardingId { get; set; }
        public Nullable<int> dmaAgreementTypeId { get; set; }
        public string AgreementType { get; set; }
        public Nullable<long> dmaCounterPartyOnBoardId { get; set; }
        public int FundID { get; set; }
        public string AgreementLongName { get; set; }
        public string AgreementShortName { get; set; }
        public string ShortFundName { get; set; }
        public string LegalFundName { get; set; }
        public string CounterpartyName { get; set; }
        public string CounterpartyFamily { get; set; }
        public string ClientName { get; set; }
        public Nullable<long> dmaClientOnBoardId { get; set; }
        public string LaunchStatus { get; set; }
        public Nullable<long> dmaOnBoardingAdminChoiceId { get; set; }
        public string AdminChoice { get; set; }
        public bool IsUmberllaFund { get; set; }
        public string CustodianCompanyName { get; set; }
        public string MarginExposureType { get; set; }
    }
}
