//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HM.Operations.Secure.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_HFundOps
    {
        public int hmFundId { get; set; }
        public Nullable<long> OnBoardFundId { get; set; }
        public string FundType { get; set; }
        public string ShortFundName { get; set; }
        public string LegalFundName { get; set; }
        public string HMRAName { get; set; }
        public string FundStatus { get; set; }
        public string BaseCurrencyShareclass { get; set; }
        public string NAVFrequency { get; set; }
        public string FundLegalStructure { get; set; }
        public string AccountingMethod { get; set; }
        public string ClientLegalEntityName { get; set; }
        public string ClientShortName { get; set; }
        public Nullable<long> dmaClientOnBoardId { get; set; }
        public string DataProviderName { get; set; }
        public Nullable<int> DataProviderId { get; set; }
        public Nullable<long> AdminId { get; set; }
        public string AdminName { get; set; }
        public string RegisterAddress { get; set; }
        public string LaunchStatus { get; set; }
        public bool IsFundAllowedForBankLoanAndIPOs { get; set; }
    }
}
