//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HM.Operations.Secure.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_hmUserCoverageDetails
    {
        public System.DateTime JoinedHedgemarkOn { get; set; }
        public double TotalYearsofExperiencePriortoHedgemark { get; set; }
        public bool IsVPAndAbove { get; set; }
        public string CommitId { get; set; }
    }
}
