
UPDATE hmsWirePurposeLkup SET IsApproved = 0 WHERE ReportName = 'Adhoc Report' AND Purpose NOT IN (
'Admin Fees',
'Audit Fees',
'CDS Payment',
'Collateral Payment',
'Custodian Transfer',
'Director Fees',
'Distribution Payment',
'Excess Cash Payment',
'FX',
'Fund Expenses',
'Futures',
'IPO Subscription',
'ISDA Payment',
'Interest Payment',
'Legal Fees',
'Loan Payment',
'Management Fees',
'Margin Payment',
'Money Market Transfer',
'OTC Derivatives',
'OTC Option Premiums',
'PB to PB Transfer',
'Private Debt Loan Payment',
'Private Investment',
'Redemption Payment',
'Repo Margin',
'Rights Offer',
'Swap Payment',
'Tax Payment',
'Trade Related',
'Tri Party',
'Vendor Payment'
)