IF NOT EXISTS(SELECT * FROM hmsWireTransferTypeLKup WHERE TransferType = 'Bank Loan/Private/IPO')
BEGIN
	SET IDENTITY_INSERT hmsWireTransferTypeLKup ON
		INSERT INTO hmsWireTransferTypeLKup (WireTransferTypeId,TransferType)VALUES(5,'Bank Loan/Private/IPO')
	SET IDENTITY_INSERT hmsWireTransferTypeLKup OFF
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME= 'hmsWirePurposeControls')
BEGIN
	CREATE TABLE [dbo].[hmsWirePurposeControls](
	[hmsWirePurposeControlId] [int] IDENTITY(1,1) NOT NULL,
	[hmsWirePurposeId] INT NOT NULL,
	[WireTransferTypeId] INT NOT NULL,
	[IsApproved] BIT NOT NULL,
	[IsApprovalRequested] BIT NOT NULL,
	[RecCreatedAt] [datetime] NOT NULL DEFAULT (getdate()),
	[RecCreatedById] [int] NOT NULL,
	[LastModifiedAt] [datetime] NOT NULL DEFAULT (getdate()),
	[LastModifiedById] [int] NOT NULL,
	CONSTRAINT UK_hmsWirePurposeControls_hmsWirePurposeId_WireTransferTypeId UNIQUE(hmsWirePurposeId,WireTransferTypeId),
	PRIMARY KEY CLUSTERED 
	(
		[hmsWirePurposeControlId] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]

	
ALTER TABLE [dbo].[hmsWirePurposeControls]  WITH CHECK ADD  CONSTRAINT [FK_hmsWirePurposeControls_hmsWirePurposeId] 
	FOREIGN KEY([hmsWirePurposeId]) REFERENCES [dbo].[hmsWirePurposeLkup] ([hmsWirePurposeId])
	
ALTER TABLE [dbo].[hmsWirePurposeControls]  WITH CHECK ADD  CONSTRAINT [FK_hmsWirePurposeControls_WireTransferTypeId] 
	FOREIGN KEY([WireTransferTypeId]) REFERENCES [dbo].[hmsWireTransferTypeLKup] ([WireTransferTypeId])

END

IF EXISTS (SELECT * FROM hmsWirePurposeLkup WHERE hmsWirePurposeId=7) BEGIN  IF NOT EXISTS(SELECT * FROM hmsWirePurposeControls WHERE hmsWirePurposeId=7 AND WireTransferTypeId =1) BEGIN INSERT INTO hmsWirePurposeControls (hmsWirePurposeId,WireTransferTypeId,IsApproved,IsApprovalRequested,RecCreatedAt,RecCreatedById,LastModifiedAt,LastModifiedById) VALUES (7,1,1,0,GETDATE(),-1,GETDATE(),-1) END END
IF EXISTS (SELECT * FROM hmsWirePurposeLkup WHERE hmsWirePurposeId=8) BEGIN  IF NOT EXISTS(SELECT * FROM hmsWirePurposeControls WHERE hmsWirePurposeId=8 AND WireTransferTypeId =1) BEGIN INSERT INTO hmsWirePurposeControls (hmsWirePurposeId,WireTransferTypeId,IsApproved,IsApprovalRequested,RecCreatedAt,RecCreatedById,LastModifiedAt,LastModifiedById) VALUES (8,1,1,0,GETDATE(),-1,GETDATE(),-1) END END
IF EXISTS (SELECT * FROM hmsWirePurposeLkup WHERE hmsWirePurposeId=9) BEGIN  IF NOT EXISTS(SELECT * FROM hmsWirePurposeControls WHERE hmsWirePurposeId=9 AND WireTransferTypeId =1) BEGIN INSERT INTO hmsWirePurposeControls (hmsWirePurposeId,WireTransferTypeId,IsApproved,IsApprovalRequested,RecCreatedAt,RecCreatedById,LastModifiedAt,LastModifiedById) VALUES (9,1,1,0,GETDATE(),-1,GETDATE(),-1) END END
IF EXISTS (SELECT * FROM hmsWirePurposeLkup WHERE hmsWirePurposeId=15) BEGIN  IF NOT EXISTS(SELECT * FROM hmsWirePurposeControls WHERE hmsWirePurposeId=15 AND WireTransferTypeId =1) BEGIN INSERT INTO hmsWirePurposeControls (hmsWirePurposeId,WireTransferTypeId,IsApproved,IsApprovalRequested,RecCreatedAt,RecCreatedById,LastModifiedAt,LastModifiedById) VALUES (15,1,1,0,GETDATE(),-1,GETDATE(),-1) END END
IF EXISTS (SELECT * FROM hmsWirePurposeLkup WHERE hmsWirePurposeId=13) BEGIN  IF NOT EXISTS(SELECT * FROM hmsWirePurposeControls WHERE hmsWirePurposeId=13 AND WireTransferTypeId =1) BEGIN INSERT INTO hmsWirePurposeControls (hmsWirePurposeId,WireTransferTypeId,IsApproved,IsApprovalRequested,RecCreatedAt,RecCreatedById,LastModifiedAt,LastModifiedById) VALUES (13,1,1,0,GETDATE(),-1,GETDATE(),-1) END END
IF EXISTS (SELECT * FROM hmsWirePurposeLkup WHERE hmsWirePurposeId=18) BEGIN  IF NOT EXISTS(SELECT * FROM hmsWirePurposeControls WHERE hmsWirePurposeId=18 AND WireTransferTypeId =1) BEGIN INSERT INTO hmsWirePurposeControls (hmsWirePurposeId,WireTransferTypeId,IsApproved,IsApprovalRequested,RecCreatedAt,RecCreatedById,LastModifiedAt,LastModifiedById) VALUES (18,1,1,0,GETDATE(),-1,GETDATE(),-1) END END
IF EXISTS (SELECT * FROM hmsWirePurposeLkup WHERE hmsWirePurposeId=16) BEGIN  IF NOT EXISTS(SELECT * FROM hmsWirePurposeControls WHERE hmsWirePurposeId=16 AND WireTransferTypeId =1) BEGIN INSERT INTO hmsWirePurposeControls (hmsWirePurposeId,WireTransferTypeId,IsApproved,IsApprovalRequested,RecCreatedAt,RecCreatedById,LastModifiedAt,LastModifiedById) VALUES (16,1,1,0,GETDATE(),-1,GETDATE(),-1) END END
IF EXISTS (SELECT * FROM hmsWirePurposeLkup WHERE hmsWirePurposeId=17) BEGIN  IF NOT EXISTS(SELECT * FROM hmsWirePurposeControls WHERE hmsWirePurposeId=17 AND WireTransferTypeId =1) BEGIN INSERT INTO hmsWirePurposeControls (hmsWirePurposeId,WireTransferTypeId,IsApproved,IsApprovalRequested,RecCreatedAt,RecCreatedById,LastModifiedAt,LastModifiedById) VALUES (17,1,1,0,GETDATE(),-1,GETDATE(),-1) END END
IF EXISTS (SELECT * FROM hmsWirePurposeLkup WHERE hmsWirePurposeId=22) BEGIN  IF NOT EXISTS(SELECT * FROM hmsWirePurposeControls WHERE hmsWirePurposeId=22 AND WireTransferTypeId =1) BEGIN INSERT INTO hmsWirePurposeControls (hmsWirePurposeId,WireTransferTypeId,IsApproved,IsApprovalRequested,RecCreatedAt,RecCreatedById,LastModifiedAt,LastModifiedById) VALUES (22,1,1,0,GETDATE(),-1,GETDATE(),-1) END END
IF EXISTS (SELECT * FROM hmsWirePurposeLkup WHERE hmsWirePurposeId=23) BEGIN  IF NOT EXISTS(SELECT * FROM hmsWirePurposeControls WHERE hmsWirePurposeId=23 AND WireTransferTypeId =1) BEGIN INSERT INTO hmsWirePurposeControls (hmsWirePurposeId,WireTransferTypeId,IsApproved,IsApprovalRequested,RecCreatedAt,RecCreatedById,LastModifiedAt,LastModifiedById) VALUES (23,1,1,0,GETDATE(),-1,GETDATE(),-1) END END
IF EXISTS (SELECT * FROM hmsWirePurposeLkup WHERE hmsWirePurposeId=24) BEGIN  IF NOT EXISTS(SELECT * FROM hmsWirePurposeControls WHERE hmsWirePurposeId=24 AND WireTransferTypeId =1) BEGIN INSERT INTO hmsWirePurposeControls (hmsWirePurposeId,WireTransferTypeId,IsApproved,IsApprovalRequested,RecCreatedAt,RecCreatedById,LastModifiedAt,LastModifiedById) VALUES (24,1,1,0,GETDATE(),-1,GETDATE(),-1) END END
IF EXISTS (SELECT * FROM hmsWirePurposeLkup WHERE hmsWirePurposeId=25) BEGIN  IF NOT EXISTS(SELECT * FROM hmsWirePurposeControls WHERE hmsWirePurposeId=25 AND WireTransferTypeId =1) BEGIN INSERT INTO hmsWirePurposeControls (hmsWirePurposeId,WireTransferTypeId,IsApproved,IsApprovalRequested,RecCreatedAt,RecCreatedById,LastModifiedAt,LastModifiedById) VALUES (25,1,1,0,GETDATE(),-1,GETDATE(),-1) END END
IF EXISTS (SELECT * FROM hmsWirePurposeLkup WHERE hmsWirePurposeId=27) BEGIN  IF NOT EXISTS(SELECT * FROM hmsWirePurposeControls WHERE hmsWirePurposeId=27 AND WireTransferTypeId =1) BEGIN INSERT INTO hmsWirePurposeControls (hmsWirePurposeId,WireTransferTypeId,IsApproved,IsApprovalRequested,RecCreatedAt,RecCreatedById,LastModifiedAt,LastModifiedById) VALUES (27,1,1,0,GETDATE(),-1,GETDATE(),-1) END END
IF EXISTS (SELECT * FROM hmsWirePurposeLkup WHERE hmsWirePurposeId=28) BEGIN  IF NOT EXISTS(SELECT * FROM hmsWirePurposeControls WHERE hmsWirePurposeId=28 AND WireTransferTypeId =1) BEGIN INSERT INTO hmsWirePurposeControls (hmsWirePurposeId,WireTransferTypeId,IsApproved,IsApprovalRequested,RecCreatedAt,RecCreatedById,LastModifiedAt,LastModifiedById) VALUES (28,1,1,0,GETDATE(),-1,GETDATE(),-1) END END
IF EXISTS (SELECT * FROM hmsWirePurposeLkup WHERE hmsWirePurposeId=30) BEGIN  IF NOT EXISTS(SELECT * FROM hmsWirePurposeControls WHERE hmsWirePurposeId=30 AND WireTransferTypeId =1) BEGIN INSERT INTO hmsWirePurposeControls (hmsWirePurposeId,WireTransferTypeId,IsApproved,IsApprovalRequested,RecCreatedAt,RecCreatedById,LastModifiedAt,LastModifiedById) VALUES (30,1,1,0,GETDATE(),-1,GETDATE(),-1) END END
IF EXISTS (SELECT * FROM hmsWirePurposeLkup WHERE hmsWirePurposeId=31) BEGIN  IF NOT EXISTS(SELECT * FROM hmsWirePurposeControls WHERE hmsWirePurposeId=31 AND WireTransferTypeId =1) BEGIN INSERT INTO hmsWirePurposeControls (hmsWirePurposeId,WireTransferTypeId,IsApproved,IsApprovalRequested,RecCreatedAt,RecCreatedById,LastModifiedAt,LastModifiedById) VALUES (31,1,1,0,GETDATE(),-1,GETDATE(),-1) END END
IF EXISTS (SELECT * FROM hmsWirePurposeLkup WHERE hmsWirePurposeId=32) BEGIN  IF NOT EXISTS(SELECT * FROM hmsWirePurposeControls WHERE hmsWirePurposeId=32 AND WireTransferTypeId =1) BEGIN INSERT INTO hmsWirePurposeControls (hmsWirePurposeId,WireTransferTypeId,IsApproved,IsApprovalRequested,RecCreatedAt,RecCreatedById,LastModifiedAt,LastModifiedById) VALUES (32,1,1,0,GETDATE(),-1,GETDATE(),-1) END END
IF EXISTS (SELECT * FROM hmsWirePurposeLkup WHERE hmsWirePurposeId=34) BEGIN  IF NOT EXISTS(SELECT * FROM hmsWirePurposeControls WHERE hmsWirePurposeId=34 AND WireTransferTypeId =1) BEGIN INSERT INTO hmsWirePurposeControls (hmsWirePurposeId,WireTransferTypeId,IsApproved,IsApprovalRequested,RecCreatedAt,RecCreatedById,LastModifiedAt,LastModifiedById) VALUES (34,1,1,0,GETDATE(),-1,GETDATE(),-1) END END
IF EXISTS (SELECT * FROM hmsWirePurposeLkup WHERE hmsWirePurposeId=35) BEGIN  IF NOT EXISTS(SELECT * FROM hmsWirePurposeControls WHERE hmsWirePurposeId=35 AND WireTransferTypeId =1) BEGIN INSERT INTO hmsWirePurposeControls (hmsWirePurposeId,WireTransferTypeId,IsApproved,IsApprovalRequested,RecCreatedAt,RecCreatedById,LastModifiedAt,LastModifiedById) VALUES (35,1,1,0,GETDATE(),-1,GETDATE(),-1) END END

IF EXISTS (SELECT * FROM hmsWirePurposeLkup WHERE hmsWirePurposeId=9) BEGIN  IF NOT EXISTS(SELECT * FROM hmsWirePurposeControls WHERE hmsWirePurposeId=9 AND WireTransferTypeId =2) BEGIN INSERT INTO hmsWirePurposeControls (hmsWirePurposeId,WireTransferTypeId,IsApproved,IsApprovalRequested,RecCreatedAt,RecCreatedById,LastModifiedAt,LastModifiedById) VALUES (9,2,1,0,GETDATE(),-1,GETDATE(),-1) END END
IF EXISTS (SELECT * FROM hmsWirePurposeLkup WHERE hmsWirePurposeId=11) BEGIN  IF NOT EXISTS(SELECT * FROM hmsWirePurposeControls WHERE hmsWirePurposeId=11 AND WireTransferTypeId =2) BEGIN INSERT INTO hmsWirePurposeControls (hmsWirePurposeId,WireTransferTypeId,IsApproved,IsApprovalRequested,RecCreatedAt,RecCreatedById,LastModifiedAt,LastModifiedById) VALUES (11,2,1,0,GETDATE(),-1,GETDATE(),-1) END END
IF EXISTS (SELECT * FROM hmsWirePurposeLkup WHERE hmsWirePurposeId=12) BEGIN  IF NOT EXISTS(SELECT * FROM hmsWirePurposeControls WHERE hmsWirePurposeId=12 AND WireTransferTypeId =2) BEGIN INSERT INTO hmsWirePurposeControls (hmsWirePurposeId,WireTransferTypeId,IsApproved,IsApprovalRequested,RecCreatedAt,RecCreatedById,LastModifiedAt,LastModifiedById) VALUES (12,2,1,0,GETDATE(),-1,GETDATE(),-1) END END
IF EXISTS (SELECT * FROM hmsWirePurposeLkup WHERE hmsWirePurposeId=13) BEGIN  IF NOT EXISTS(SELECT * FROM hmsWirePurposeControls WHERE hmsWirePurposeId=13 AND WireTransferTypeId =2) BEGIN INSERT INTO hmsWirePurposeControls (hmsWirePurposeId,WireTransferTypeId,IsApproved,IsApprovalRequested,RecCreatedAt,RecCreatedById,LastModifiedAt,LastModifiedById) VALUES (13,2,1,0,GETDATE(),-1,GETDATE(),-1) END END
IF EXISTS (SELECT * FROM hmsWirePurposeLkup WHERE hmsWirePurposeId=22) BEGIN  IF NOT EXISTS(SELECT * FROM hmsWirePurposeControls WHERE hmsWirePurposeId=22 AND WireTransferTypeId =2) BEGIN INSERT INTO hmsWirePurposeControls (hmsWirePurposeId,WireTransferTypeId,IsApproved,IsApprovalRequested,RecCreatedAt,RecCreatedById,LastModifiedAt,LastModifiedById) VALUES (22,2,1,0,GETDATE(),-1,GETDATE(),-1) END END
IF EXISTS (SELECT * FROM hmsWirePurposeLkup WHERE hmsWirePurposeId=23) BEGIN  IF NOT EXISTS(SELECT * FROM hmsWirePurposeControls WHERE hmsWirePurposeId=23 AND WireTransferTypeId =2) BEGIN INSERT INTO hmsWirePurposeControls (hmsWirePurposeId,WireTransferTypeId,IsApproved,IsApprovalRequested,RecCreatedAt,RecCreatedById,LastModifiedAt,LastModifiedById) VALUES (23,2,1,0,GETDATE(),-1,GETDATE(),-1) END END
IF EXISTS (SELECT * FROM hmsWirePurposeLkup WHERE hmsWirePurposeId=26) BEGIN  IF NOT EXISTS(SELECT * FROM hmsWirePurposeControls WHERE hmsWirePurposeId=26 AND WireTransferTypeId =2) BEGIN INSERT INTO hmsWirePurposeControls (hmsWirePurposeId,WireTransferTypeId,IsApproved,IsApprovalRequested,RecCreatedAt,RecCreatedById,LastModifiedAt,LastModifiedById) VALUES (26,2,1,0,GETDATE(),-1,GETDATE(),-1) END END
IF EXISTS (SELECT * FROM hmsWirePurposeLkup WHERE hmsWirePurposeId=29) BEGIN  IF NOT EXISTS(SELECT * FROM hmsWirePurposeControls WHERE hmsWirePurposeId=29 AND WireTransferTypeId =2) BEGIN INSERT INTO hmsWirePurposeControls (hmsWirePurposeId,WireTransferTypeId,IsApproved,IsApprovalRequested,RecCreatedAt,RecCreatedById,LastModifiedAt,LastModifiedById) VALUES (29,2,1,0,GETDATE(),-1,GETDATE(),-1) END END

IF EXISTS (SELECT * FROM hmsWirePurposeLkup WHERE hmsWirePurposeId=5) BEGIN  IF NOT EXISTS(SELECT * FROM hmsWirePurposeControls WHERE hmsWirePurposeId=5 AND WireTransferTypeId =3) BEGIN INSERT INTO hmsWirePurposeControls (hmsWirePurposeId,WireTransferTypeId,IsApproved,IsApprovalRequested,RecCreatedAt,RecCreatedById,LastModifiedAt,LastModifiedById) VALUES (5,3,1,0,GETDATE(),-1,GETDATE(),-1) END END
IF EXISTS (SELECT * FROM hmsWirePurposeLkup WHERE hmsWirePurposeId=6) BEGIN  IF NOT EXISTS(SELECT * FROM hmsWirePurposeControls WHERE hmsWirePurposeId=6 AND WireTransferTypeId =3) BEGIN INSERT INTO hmsWirePurposeControls (hmsWirePurposeId,WireTransferTypeId,IsApproved,IsApprovalRequested,RecCreatedAt,RecCreatedById,LastModifiedAt,LastModifiedById) VALUES (6,3,1,0,GETDATE(),-1,GETDATE(),-1) END END
IF EXISTS (SELECT * FROM hmsWirePurposeLkup WHERE hmsWirePurposeId=10) BEGIN  IF NOT EXISTS(SELECT * FROM hmsWirePurposeControls WHERE hmsWirePurposeId=10 AND WireTransferTypeId =3) BEGIN INSERT INTO hmsWirePurposeControls (hmsWirePurposeId,WireTransferTypeId,IsApproved,IsApprovalRequested,RecCreatedAt,RecCreatedById,LastModifiedAt,LastModifiedById) VALUES (10,3,1,0,GETDATE(),-1,GETDATE(),-1) END END
IF EXISTS (SELECT * FROM hmsWirePurposeLkup WHERE hmsWirePurposeId=19) BEGIN  IF NOT EXISTS(SELECT * FROM hmsWirePurposeControls WHERE hmsWirePurposeId=19 AND WireTransferTypeId =3) BEGIN INSERT INTO hmsWirePurposeControls (hmsWirePurposeId,WireTransferTypeId,IsApproved,IsApprovalRequested,RecCreatedAt,RecCreatedById,LastModifiedAt,LastModifiedById) VALUES (19,3,1,0,GETDATE(),-1,GETDATE(),-1) END END
IF EXISTS (SELECT * FROM hmsWirePurposeLkup WHERE hmsWirePurposeId=21) BEGIN  IF NOT EXISTS(SELECT * FROM hmsWirePurposeControls WHERE hmsWirePurposeId=21 AND WireTransferTypeId =3) BEGIN INSERT INTO hmsWirePurposeControls (hmsWirePurposeId,WireTransferTypeId,IsApproved,IsApprovalRequested,RecCreatedAt,RecCreatedById,LastModifiedAt,LastModifiedById) VALUES (21,3,1,0,GETDATE(),-1,GETDATE(),-1) END END
IF EXISTS (SELECT * FROM hmsWirePurposeLkup WHERE hmsWirePurposeId=33) BEGIN  IF NOT EXISTS(SELECT * FROM hmsWirePurposeControls WHERE hmsWirePurposeId=33 AND WireTransferTypeId =3) BEGIN INSERT INTO hmsWirePurposeControls (hmsWirePurposeId,WireTransferTypeId,IsApproved,IsApprovalRequested,RecCreatedAt,RecCreatedById,LastModifiedAt,LastModifiedById) VALUES (33,3,1,0,GETDATE(),-1,GETDATE(),-1) END END


IF EXISTS (SELECT * FROM hmsWirePurposeLkup WHERE hmsWirePurposeId=5) BEGIN  IF NOT EXISTS(SELECT * FROM hmsWirePurposeControls WHERE hmsWirePurposeId=5 AND WireTransferTypeId =4) BEGIN INSERT INTO hmsWirePurposeControls (hmsWirePurposeId,WireTransferTypeId,IsApproved,IsApprovalRequested,RecCreatedAt,RecCreatedById,LastModifiedAt,LastModifiedById) VALUES (5,4,1,0,GETDATE(),-1,GETDATE(),-1) END END
IF EXISTS (SELECT * FROM hmsWirePurposeLkup WHERE hmsWirePurposeId=6) BEGIN  IF NOT EXISTS(SELECT * FROM hmsWirePurposeControls WHERE hmsWirePurposeId=6 AND WireTransferTypeId =4) BEGIN INSERT INTO hmsWirePurposeControls (hmsWirePurposeId,WireTransferTypeId,IsApproved,IsApprovalRequested,RecCreatedAt,RecCreatedById,LastModifiedAt,LastModifiedById) VALUES (6,4,1,0,GETDATE(),-1,GETDATE(),-1) END END
IF EXISTS (SELECT * FROM hmsWirePurposeLkup WHERE hmsWirePurposeId=7) BEGIN  IF NOT EXISTS(SELECT * FROM hmsWirePurposeControls WHERE hmsWirePurposeId=7 AND WireTransferTypeId =4) BEGIN INSERT INTO hmsWirePurposeControls (hmsWirePurposeId,WireTransferTypeId,IsApproved,IsApprovalRequested,RecCreatedAt,RecCreatedById,LastModifiedAt,LastModifiedById) VALUES (7,4,1,0,GETDATE(),-1,GETDATE(),-1) END END
IF EXISTS (SELECT * FROM hmsWirePurposeLkup WHERE hmsWirePurposeId=8) BEGIN  IF NOT EXISTS(SELECT * FROM hmsWirePurposeControls WHERE hmsWirePurposeId=8 AND WireTransferTypeId =4) BEGIN INSERT INTO hmsWirePurposeControls (hmsWirePurposeId,WireTransferTypeId,IsApproved,IsApprovalRequested,RecCreatedAt,RecCreatedById,LastModifiedAt,LastModifiedById) VALUES (8,4,1,0,GETDATE(),-1,GETDATE(),-1) END END
IF EXISTS (SELECT * FROM hmsWirePurposeLkup WHERE hmsWirePurposeId=9) BEGIN  IF NOT EXISTS(SELECT * FROM hmsWirePurposeControls WHERE hmsWirePurposeId=9 AND WireTransferTypeId =4) BEGIN INSERT INTO hmsWirePurposeControls (hmsWirePurposeId,WireTransferTypeId,IsApproved,IsApprovalRequested,RecCreatedAt,RecCreatedById,LastModifiedAt,LastModifiedById) VALUES (9,4,1,0,GETDATE(),-1,GETDATE(),-1) END END
IF EXISTS (SELECT * FROM hmsWirePurposeLkup WHERE hmsWirePurposeId=10) BEGIN  IF NOT EXISTS(SELECT * FROM hmsWirePurposeControls WHERE hmsWirePurposeId=10 AND WireTransferTypeId =4) BEGIN INSERT INTO hmsWirePurposeControls (hmsWirePurposeId,WireTransferTypeId,IsApproved,IsApprovalRequested,RecCreatedAt,RecCreatedById,LastModifiedAt,LastModifiedById) VALUES (10,4,1,0,GETDATE(),-1,GETDATE(),-1) END END
IF EXISTS (SELECT * FROM hmsWirePurposeLkup WHERE hmsWirePurposeId=11) BEGIN  IF NOT EXISTS(SELECT * FROM hmsWirePurposeControls WHERE hmsWirePurposeId=11 AND WireTransferTypeId =4) BEGIN INSERT INTO hmsWirePurposeControls (hmsWirePurposeId,WireTransferTypeId,IsApproved,IsApprovalRequested,RecCreatedAt,RecCreatedById,LastModifiedAt,LastModifiedById) VALUES (11,4,1,0,GETDATE(),-1,GETDATE(),-1) END END
IF EXISTS (SELECT * FROM hmsWirePurposeLkup WHERE hmsWirePurposeId=12) BEGIN  IF NOT EXISTS(SELECT * FROM hmsWirePurposeControls WHERE hmsWirePurposeId=12 AND WireTransferTypeId =4) BEGIN INSERT INTO hmsWirePurposeControls (hmsWirePurposeId,WireTransferTypeId,IsApproved,IsApprovalRequested,RecCreatedAt,RecCreatedById,LastModifiedAt,LastModifiedById) VALUES (12,4,1,0,GETDATE(),-1,GETDATE(),-1) END END
IF EXISTS (SELECT * FROM hmsWirePurposeLkup WHERE hmsWirePurposeId=14) BEGIN  IF NOT EXISTS(SELECT * FROM hmsWirePurposeControls WHERE hmsWirePurposeId=14 AND WireTransferTypeId =4) BEGIN INSERT INTO hmsWirePurposeControls (hmsWirePurposeId,WireTransferTypeId,IsApproved,IsApprovalRequested,RecCreatedAt,RecCreatedById,LastModifiedAt,LastModifiedById) VALUES (14,4,1,0,GETDATE(),-1,GETDATE(),-1) END END
IF EXISTS (SELECT * FROM hmsWirePurposeLkup WHERE hmsWirePurposeId=15) BEGIN  IF NOT EXISTS(SELECT * FROM hmsWirePurposeControls WHERE hmsWirePurposeId=15 AND WireTransferTypeId =4) BEGIN INSERT INTO hmsWirePurposeControls (hmsWirePurposeId,WireTransferTypeId,IsApproved,IsApprovalRequested,RecCreatedAt,RecCreatedById,LastModifiedAt,LastModifiedById) VALUES (15,4,1,0,GETDATE(),-1,GETDATE(),-1) END END
IF EXISTS (SELECT * FROM hmsWirePurposeLkup WHERE hmsWirePurposeId=13) BEGIN  IF NOT EXISTS(SELECT * FROM hmsWirePurposeControls WHERE hmsWirePurposeId=13 AND WireTransferTypeId =4) BEGIN INSERT INTO hmsWirePurposeControls (hmsWirePurposeId,WireTransferTypeId,IsApproved,IsApprovalRequested,RecCreatedAt,RecCreatedById,LastModifiedAt,LastModifiedById) VALUES (13,4,1,0,GETDATE(),-1,GETDATE(),-1) END END
IF EXISTS (SELECT * FROM hmsWirePurposeLkup WHERE hmsWirePurposeId=18) BEGIN  IF NOT EXISTS(SELECT * FROM hmsWirePurposeControls WHERE hmsWirePurposeId=18 AND WireTransferTypeId =4) BEGIN INSERT INTO hmsWirePurposeControls (hmsWirePurposeId,WireTransferTypeId,IsApproved,IsApprovalRequested,RecCreatedAt,RecCreatedById,LastModifiedAt,LastModifiedById) VALUES (18,4,1,0,GETDATE(),-1,GETDATE(),-1) END END
IF EXISTS (SELECT * FROM hmsWirePurposeLkup WHERE hmsWirePurposeId=16) BEGIN  IF NOT EXISTS(SELECT * FROM hmsWirePurposeControls WHERE hmsWirePurposeId=16 AND WireTransferTypeId =4) BEGIN INSERT INTO hmsWirePurposeControls (hmsWirePurposeId,WireTransferTypeId,IsApproved,IsApprovalRequested,RecCreatedAt,RecCreatedById,LastModifiedAt,LastModifiedById) VALUES (16,4,1,0,GETDATE(),-1,GETDATE(),-1) END END
IF EXISTS (SELECT * FROM hmsWirePurposeLkup WHERE hmsWirePurposeId=17) BEGIN  IF NOT EXISTS(SELECT * FROM hmsWirePurposeControls WHERE hmsWirePurposeId=17 AND WireTransferTypeId =4) BEGIN INSERT INTO hmsWirePurposeControls (hmsWirePurposeId,WireTransferTypeId,IsApproved,IsApprovalRequested,RecCreatedAt,RecCreatedById,LastModifiedAt,LastModifiedById) VALUES (17,4,1,0,GETDATE(),-1,GETDATE(),-1) END END
IF EXISTS (SELECT * FROM hmsWirePurposeLkup WHERE hmsWirePurposeId=19) BEGIN  IF NOT EXISTS(SELECT * FROM hmsWirePurposeControls WHERE hmsWirePurposeId=19 AND WireTransferTypeId =4) BEGIN INSERT INTO hmsWirePurposeControls (hmsWirePurposeId,WireTransferTypeId,IsApproved,IsApprovalRequested,RecCreatedAt,RecCreatedById,LastModifiedAt,LastModifiedById) VALUES (19,4,1,0,GETDATE(),-1,GETDATE(),-1) END END
IF EXISTS (SELECT * FROM hmsWirePurposeLkup WHERE hmsWirePurposeId=20) BEGIN  IF NOT EXISTS(SELECT * FROM hmsWirePurposeControls WHERE hmsWirePurposeId=20 AND WireTransferTypeId =4) BEGIN INSERT INTO hmsWirePurposeControls (hmsWirePurposeId,WireTransferTypeId,IsApproved,IsApprovalRequested,RecCreatedAt,RecCreatedById,LastModifiedAt,LastModifiedById) VALUES (20,4,1,0,GETDATE(),-1,GETDATE(),-1) END END
IF EXISTS (SELECT * FROM hmsWirePurposeLkup WHERE hmsWirePurposeId=21) BEGIN  IF NOT EXISTS(SELECT * FROM hmsWirePurposeControls WHERE hmsWirePurposeId=21 AND WireTransferTypeId =4) BEGIN INSERT INTO hmsWirePurposeControls (hmsWirePurposeId,WireTransferTypeId,IsApproved,IsApprovalRequested,RecCreatedAt,RecCreatedById,LastModifiedAt,LastModifiedById) VALUES (21,4,1,0,GETDATE(),-1,GETDATE(),-1) END END
IF EXISTS (SELECT * FROM hmsWirePurposeLkup WHERE hmsWirePurposeId=22) BEGIN  IF NOT EXISTS(SELECT * FROM hmsWirePurposeControls WHERE hmsWirePurposeId=22 AND WireTransferTypeId =4) BEGIN INSERT INTO hmsWirePurposeControls (hmsWirePurposeId,WireTransferTypeId,IsApproved,IsApprovalRequested,RecCreatedAt,RecCreatedById,LastModifiedAt,LastModifiedById) VALUES (22,4,1,0,GETDATE(),-1,GETDATE(),-1) END END
IF EXISTS (SELECT * FROM hmsWirePurposeLkup WHERE hmsWirePurposeId=23) BEGIN  IF NOT EXISTS(SELECT * FROM hmsWirePurposeControls WHERE hmsWirePurposeId=23 AND WireTransferTypeId =4) BEGIN INSERT INTO hmsWirePurposeControls (hmsWirePurposeId,WireTransferTypeId,IsApproved,IsApprovalRequested,RecCreatedAt,RecCreatedById,LastModifiedAt,LastModifiedById) VALUES (23,4,1,0,GETDATE(),-1,GETDATE(),-1) END END
IF EXISTS (SELECT * FROM hmsWirePurposeLkup WHERE hmsWirePurposeId=24) BEGIN  IF NOT EXISTS(SELECT * FROM hmsWirePurposeControls WHERE hmsWirePurposeId=24 AND WireTransferTypeId =4) BEGIN INSERT INTO hmsWirePurposeControls (hmsWirePurposeId,WireTransferTypeId,IsApproved,IsApprovalRequested,RecCreatedAt,RecCreatedById,LastModifiedAt,LastModifiedById) VALUES (24,4,1,0,GETDATE(),-1,GETDATE(),-1) END END
IF EXISTS (SELECT * FROM hmsWirePurposeLkup WHERE hmsWirePurposeId=25) BEGIN  IF NOT EXISTS(SELECT * FROM hmsWirePurposeControls WHERE hmsWirePurposeId=25 AND WireTransferTypeId =4) BEGIN INSERT INTO hmsWirePurposeControls (hmsWirePurposeId,WireTransferTypeId,IsApproved,IsApprovalRequested,RecCreatedAt,RecCreatedById,LastModifiedAt,LastModifiedById) VALUES (25,4,1,0,GETDATE(),-1,GETDATE(),-1) END END
IF EXISTS (SELECT * FROM hmsWirePurposeLkup WHERE hmsWirePurposeId=26) BEGIN  IF NOT EXISTS(SELECT * FROM hmsWirePurposeControls WHERE hmsWirePurposeId=26 AND WireTransferTypeId =4) BEGIN INSERT INTO hmsWirePurposeControls (hmsWirePurposeId,WireTransferTypeId,IsApproved,IsApprovalRequested,RecCreatedAt,RecCreatedById,LastModifiedAt,LastModifiedById) VALUES (26,4,1,0,GETDATE(),-1,GETDATE(),-1) END END
IF EXISTS (SELECT * FROM hmsWirePurposeLkup WHERE hmsWirePurposeId=27) BEGIN  IF NOT EXISTS(SELECT * FROM hmsWirePurposeControls WHERE hmsWirePurposeId=27 AND WireTransferTypeId =4) BEGIN INSERT INTO hmsWirePurposeControls (hmsWirePurposeId,WireTransferTypeId,IsApproved,IsApprovalRequested,RecCreatedAt,RecCreatedById,LastModifiedAt,LastModifiedById) VALUES (27,4,1,0,GETDATE(),-1,GETDATE(),-1) END END
IF EXISTS (SELECT * FROM hmsWirePurposeLkup WHERE hmsWirePurposeId=28) BEGIN  IF NOT EXISTS(SELECT * FROM hmsWirePurposeControls WHERE hmsWirePurposeId=28 AND WireTransferTypeId =4) BEGIN INSERT INTO hmsWirePurposeControls (hmsWirePurposeId,WireTransferTypeId,IsApproved,IsApprovalRequested,RecCreatedAt,RecCreatedById,LastModifiedAt,LastModifiedById) VALUES (28,4,1,0,GETDATE(),-1,GETDATE(),-1) END END
IF EXISTS (SELECT * FROM hmsWirePurposeLkup WHERE hmsWirePurposeId=29) BEGIN  IF NOT EXISTS(SELECT * FROM hmsWirePurposeControls WHERE hmsWirePurposeId=29 AND WireTransferTypeId =4) BEGIN INSERT INTO hmsWirePurposeControls (hmsWirePurposeId,WireTransferTypeId,IsApproved,IsApprovalRequested,RecCreatedAt,RecCreatedById,LastModifiedAt,LastModifiedById) VALUES (29,4,1,0,GETDATE(),-1,GETDATE(),-1) END END
IF EXISTS (SELECT * FROM hmsWirePurposeLkup WHERE hmsWirePurposeId=30) BEGIN  IF NOT EXISTS(SELECT * FROM hmsWirePurposeControls WHERE hmsWirePurposeId=30 AND WireTransferTypeId =4) BEGIN INSERT INTO hmsWirePurposeControls (hmsWirePurposeId,WireTransferTypeId,IsApproved,IsApprovalRequested,RecCreatedAt,RecCreatedById,LastModifiedAt,LastModifiedById) VALUES (30,4,1,0,GETDATE(),-1,GETDATE(),-1) END END
IF EXISTS (SELECT * FROM hmsWirePurposeLkup WHERE hmsWirePurposeId=31) BEGIN  IF NOT EXISTS(SELECT * FROM hmsWirePurposeControls WHERE hmsWirePurposeId=31 AND WireTransferTypeId =4) BEGIN INSERT INTO hmsWirePurposeControls (hmsWirePurposeId,WireTransferTypeId,IsApproved,IsApprovalRequested,RecCreatedAt,RecCreatedById,LastModifiedAt,LastModifiedById) VALUES (31,4,1,0,GETDATE(),-1,GETDATE(),-1) END END
IF EXISTS (SELECT * FROM hmsWirePurposeLkup WHERE hmsWirePurposeId=32) BEGIN  IF NOT EXISTS(SELECT * FROM hmsWirePurposeControls WHERE hmsWirePurposeId=32 AND WireTransferTypeId =4) BEGIN INSERT INTO hmsWirePurposeControls (hmsWirePurposeId,WireTransferTypeId,IsApproved,IsApprovalRequested,RecCreatedAt,RecCreatedById,LastModifiedAt,LastModifiedById) VALUES (32,4,1,0,GETDATE(),-1,GETDATE(),-1) END END
IF EXISTS (SELECT * FROM hmsWirePurposeLkup WHERE hmsWirePurposeId=33) BEGIN  IF NOT EXISTS(SELECT * FROM hmsWirePurposeControls WHERE hmsWirePurposeId=33 AND WireTransferTypeId =4) BEGIN INSERT INTO hmsWirePurposeControls (hmsWirePurposeId,WireTransferTypeId,IsApproved,IsApprovalRequested,RecCreatedAt,RecCreatedById,LastModifiedAt,LastModifiedById) VALUES (33,4,1,0,GETDATE(),-1,GETDATE(),-1) END END
IF EXISTS (SELECT * FROM hmsWirePurposeLkup WHERE hmsWirePurposeId=34) BEGIN  IF NOT EXISTS(SELECT * FROM hmsWirePurposeControls WHERE hmsWirePurposeId=34 AND WireTransferTypeId =4) BEGIN INSERT INTO hmsWirePurposeControls (hmsWirePurposeId,WireTransferTypeId,IsApproved,IsApprovalRequested,RecCreatedAt,RecCreatedById,LastModifiedAt,LastModifiedById) VALUES (34,4,1,0,GETDATE(),-1,GETDATE(),-1) END END
IF EXISTS (SELECT * FROM hmsWirePurposeLkup WHERE hmsWirePurposeId=35) BEGIN  IF NOT EXISTS(SELECT * FROM hmsWirePurposeControls WHERE hmsWirePurposeId=35 AND WireTransferTypeId =4) BEGIN INSERT INTO hmsWirePurposeControls (hmsWirePurposeId,WireTransferTypeId,IsApproved,IsApprovalRequested,RecCreatedAt,RecCreatedById,LastModifiedAt,LastModifiedById) VALUES (35,4,1,0,GETDATE(),-1,GETDATE(),-1) END END
IF EXISTS (SELECT * FROM hmsWirePurposeLkup WHERE hmsWirePurposeId=36) BEGIN  IF NOT EXISTS(SELECT * FROM hmsWirePurposeControls WHERE hmsWirePurposeId=36 AND WireTransferTypeId =4) BEGIN INSERT INTO hmsWirePurposeControls (hmsWirePurposeId,WireTransferTypeId,IsApproved,IsApprovalRequested,RecCreatedAt,RecCreatedById,LastModifiedAt,LastModifiedById) VALUES (36,4,1,0,GETDATE(),-1,GETDATE(),-1) END END


IF EXISTS (SELECT * FROM hmsWirePurposeLkup WHERE hmsWirePurposeId=7) BEGIN  IF NOT EXISTS(SELECT * FROM hmsWirePurposeControls WHERE hmsWirePurposeId=7 AND WireTransferTypeId =5) BEGIN INSERT INTO hmsWirePurposeControls (hmsWirePurposeId,WireTransferTypeId,IsApproved,IsApprovalRequested,RecCreatedAt,RecCreatedById,LastModifiedAt,LastModifiedById) VALUES (7,5,1,0,GETDATE(),-1,GETDATE(),-1) END END
IF EXISTS (SELECT * FROM hmsWirePurposeLkup WHERE hmsWirePurposeId=16) BEGIN  IF NOT EXISTS(SELECT * FROM hmsWirePurposeControls WHERE hmsWirePurposeId=16 AND WireTransferTypeId =5) BEGIN INSERT INTO hmsWirePurposeControls (hmsWirePurposeId,WireTransferTypeId,IsApproved,IsApprovalRequested,RecCreatedAt,RecCreatedById,LastModifiedAt,LastModifiedById) VALUES (16,5,1,0,GETDATE(),-1,GETDATE(),-1) END END
IF EXISTS (SELECT * FROM hmsWirePurposeLkup WHERE hmsWirePurposeId=17) BEGIN  IF NOT EXISTS(SELECT * FROM hmsWirePurposeControls WHERE hmsWirePurposeId=17 AND WireTransferTypeId =5) BEGIN INSERT INTO hmsWirePurposeControls (hmsWirePurposeId,WireTransferTypeId,IsApproved,IsApprovalRequested,RecCreatedAt,RecCreatedById,LastModifiedAt,LastModifiedById) VALUES (17,5,1,0,GETDATE(),-1,GETDATE(),-1) END END
IF EXISTS (SELECT * FROM hmsWirePurposeLkup WHERE hmsWirePurposeId=20) BEGIN  IF NOT EXISTS(SELECT * FROM hmsWirePurposeControls WHERE hmsWirePurposeId=20 AND WireTransferTypeId =5) BEGIN INSERT INTO hmsWirePurposeControls (hmsWirePurposeId,WireTransferTypeId,IsApproved,IsApprovalRequested,RecCreatedAt,RecCreatedById,LastModifiedAt,LastModifiedById) VALUES (20,5,1,0,GETDATE(),-1,GETDATE(),-1) END END
IF EXISTS (SELECT * FROM hmsWirePurposeLkup WHERE hmsWirePurposeId=24) BEGIN  IF NOT EXISTS(SELECT * FROM hmsWirePurposeControls WHERE hmsWirePurposeId=24 AND WireTransferTypeId =5) BEGIN INSERT INTO hmsWirePurposeControls (hmsWirePurposeId,WireTransferTypeId,IsApproved,IsApprovalRequested,RecCreatedAt,RecCreatedById,LastModifiedAt,LastModifiedById) VALUES (24,5,1,0,GETDATE(),-1,GETDATE(),-1) END END
IF EXISTS (SELECT * FROM hmsWirePurposeLkup WHERE hmsWirePurposeId=25) BEGIN  IF NOT EXISTS(SELECT * FROM hmsWirePurposeControls WHERE hmsWirePurposeId=25 AND WireTransferTypeId =5) BEGIN INSERT INTO hmsWirePurposeControls (hmsWirePurposeId,WireTransferTypeId,IsApproved,IsApprovalRequested,RecCreatedAt,RecCreatedById,LastModifiedAt,LastModifiedById) VALUES (25,5,1,0,GETDATE(),-1,GETDATE(),-1) END END
IF EXISTS (SELECT * FROM hmsWirePurposeLkup WHERE hmsWirePurposeId=27) BEGIN  IF NOT EXISTS(SELECT * FROM hmsWirePurposeControls WHERE hmsWirePurposeId=27 AND WireTransferTypeId =5) BEGIN INSERT INTO hmsWirePurposeControls (hmsWirePurposeId,WireTransferTypeId,IsApproved,IsApprovalRequested,RecCreatedAt,RecCreatedById,LastModifiedAt,LastModifiedById) VALUES (27,5,1,0,GETDATE(),-1,GETDATE(),-1) END END
IF EXISTS (SELECT * FROM hmsWirePurposeLkup WHERE hmsWirePurposeId=28) BEGIN  IF NOT EXISTS(SELECT * FROM hmsWirePurposeControls WHERE hmsWirePurposeId=28 AND WireTransferTypeId =5) BEGIN INSERT INTO hmsWirePurposeControls (hmsWirePurposeId,WireTransferTypeId,IsApproved,IsApprovalRequested,RecCreatedAt,RecCreatedById,LastModifiedAt,LastModifiedById) VALUES (28,5,1,0,GETDATE(),-1,GETDATE(),-1) END END
IF EXISTS (SELECT * FROM hmsWirePurposeLkup WHERE hmsWirePurposeId=31) BEGIN  IF NOT EXISTS(SELECT * FROM hmsWirePurposeControls WHERE hmsWirePurposeId=31 AND WireTransferTypeId =5) BEGIN INSERT INTO hmsWirePurposeControls (hmsWirePurposeId,WireTransferTypeId,IsApproved,IsApprovalRequested,RecCreatedAt,RecCreatedById,LastModifiedAt,LastModifiedById) VALUES (31,5,1,0,GETDATE(),-1,GETDATE(),-1) END END
IF EXISTS (SELECT * FROM hmsWirePurposeLkup WHERE hmsWirePurposeId=32) BEGIN  IF NOT EXISTS(SELECT * FROM hmsWirePurposeControls WHERE hmsWirePurposeId=32 AND WireTransferTypeId =5) BEGIN INSERT INTO hmsWirePurposeControls (hmsWirePurposeId,WireTransferTypeId,IsApproved,IsApprovalRequested,RecCreatedAt,RecCreatedById,LastModifiedAt,LastModifiedById) VALUES (32,5,1,0,GETDATE(),-1,GETDATE(),-1) END END
IF EXISTS (SELECT * FROM hmsWirePurposeLkup WHERE hmsWirePurposeId=34) BEGIN  IF NOT EXISTS(SELECT * FROM hmsWirePurposeControls WHERE hmsWirePurposeId=34 AND WireTransferTypeId =5) BEGIN INSERT INTO hmsWirePurposeControls (hmsWirePurposeId,WireTransferTypeId,IsApproved,IsApprovalRequested,RecCreatedAt,RecCreatedById,LastModifiedAt,LastModifiedById) VALUES (34,5,1,0,GETDATE(),-1,GETDATE(),-1) END END
