IF NOT EXISTS(SELECT 8 FROM hmsWirePurposeLkup WHERE CreatedBy = -1  AND ReportName = 'Adhoc Report' AND Purpose = 'Admin Fees')
BEGIN

INSERT INTO [hmsWirePurposeLkup] ([ReportName], [Purpose],[CreatedAt],[CreatedBy],[ModifiedBy],[ModifiedAt],[IsApproved]) VALUES('Adhoc Report', 'Admin Fees',GETDATE(),-1, NULL, NULL, 1)
INSERT INTO [hmsWirePurposeLkup] ([ReportName], [Purpose],[CreatedAt],[CreatedBy],[ModifiedBy],[ModifiedAt],[IsApproved]) VALUES('Adhoc Report', 'Audit Fees',GETDATE(),-1, NULL, NULL, 1)
INSERT INTO [hmsWirePurposeLkup] ([ReportName], [Purpose],[CreatedAt],[CreatedBy],[ModifiedBy],[ModifiedAt],[IsApproved]) VALUES('Adhoc Report', 'CDS Payment',GETDATE(),-1, NULL, NULL, 1)
INSERT INTO [hmsWirePurposeLkup] ([ReportName], [Purpose],[CreatedAt],[CreatedBy],[ModifiedBy],[ModifiedAt],[IsApproved]) VALUES('Adhoc Report', 'Collateral Payment',GETDATE(),-1, NULL, NULL, 1)
INSERT INTO [hmsWirePurposeLkup] ([ReportName], [Purpose],[CreatedAt],[CreatedBy],[ModifiedBy],[ModifiedAt],[IsApproved]) VALUES('Adhoc Report', 'Custodian Transfer',GETDATE(),-1, NULL, NULL, 1)
INSERT INTO [hmsWirePurposeLkup] ([ReportName], [Purpose],[CreatedAt],[CreatedBy],[ModifiedBy],[ModifiedAt],[IsApproved]) VALUES('Adhoc Report', 'Director Fees',GETDATE(),-1, NULL, NULL, 1)
INSERT INTO [hmsWirePurposeLkup] ([ReportName], [Purpose],[CreatedAt],[CreatedBy],[ModifiedBy],[ModifiedAt],[IsApproved]) VALUES('Adhoc Report', 'Distribution Payment',GETDATE(),-1, NULL, NULL, 1)
INSERT INTO [hmsWirePurposeLkup] ([ReportName], [Purpose],[CreatedAt],[CreatedBy],[ModifiedBy],[ModifiedAt],[IsApproved]) VALUES('Adhoc Report', 'Excess Cash Payment',GETDATE(),-1, NULL, NULL, 1)
INSERT INTO [hmsWirePurposeLkup] ([ReportName], [Purpose],[CreatedAt],[CreatedBy],[ModifiedBy],[ModifiedAt],[IsApproved]) VALUES('Adhoc Report', 'FX',GETDATE(),-1, NULL, NULL, 1)
INSERT INTO [hmsWirePurposeLkup] ([ReportName], [Purpose],[CreatedAt],[CreatedBy],[ModifiedBy],[ModifiedAt],[IsApproved]) VALUES('Adhoc Report', 'Fund Expenses',GETDATE(),-1, NULL, NULL, 1)
INSERT INTO [hmsWirePurposeLkup] ([ReportName], [Purpose],[CreatedAt],[CreatedBy],[ModifiedBy],[ModifiedAt],[IsApproved]) VALUES('Adhoc Report', 'Futures',GETDATE(),-1, NULL, NULL, 1)
INSERT INTO [hmsWirePurposeLkup] ([ReportName], [Purpose],[CreatedAt],[CreatedBy],[ModifiedBy],[ModifiedAt],[IsApproved]) VALUES('Adhoc Report', 'IPO Subscription',GETDATE(),-1, NULL, NULL, 1)
INSERT INTO [hmsWirePurposeLkup] ([ReportName], [Purpose],[CreatedAt],[CreatedBy],[ModifiedBy],[ModifiedAt],[IsApproved]) VALUES('Adhoc Report', 'ISDA Payment',GETDATE(),-1, NULL, NULL, 1)
INSERT INTO [hmsWirePurposeLkup] ([ReportName], [Purpose],[CreatedAt],[CreatedBy],[ModifiedBy],[ModifiedAt],[IsApproved]) VALUES('Adhoc Report', 'Interest Payment',GETDATE(),-1, NULL, NULL, 1)
INSERT INTO [hmsWirePurposeLkup] ([ReportName], [Purpose],[CreatedAt],[CreatedBy],[ModifiedBy],[ModifiedAt],[IsApproved]) VALUES('Adhoc Report', 'Legal Fees',GETDATE(),-1, NULL, NULL, 1)
INSERT INTO [hmsWirePurposeLkup] ([ReportName], [Purpose],[CreatedAt],[CreatedBy],[ModifiedBy],[ModifiedAt],[IsApproved]) VALUES('Adhoc Report', 'Loan Payment',GETDATE(),-1, NULL, NULL, 1)
INSERT INTO [hmsWirePurposeLkup] ([ReportName], [Purpose],[CreatedAt],[CreatedBy],[ModifiedBy],[ModifiedAt],[IsApproved]) VALUES('Adhoc Report', 'Management Fees',GETDATE(),-1, NULL, NULL, 1)
INSERT INTO [hmsWirePurposeLkup] ([ReportName], [Purpose],[CreatedAt],[CreatedBy],[ModifiedBy],[ModifiedAt],[IsApproved]) VALUES('Adhoc Report', 'Margin Payment',GETDATE(),-1, NULL, NULL, 1)
INSERT INTO [hmsWirePurposeLkup] ([ReportName], [Purpose],[CreatedAt],[CreatedBy],[ModifiedBy],[ModifiedAt],[IsApproved]) VALUES('Adhoc Report', 'Money Market Transfer',GETDATE(),-1, NULL, NULL, 1)
INSERT INTO [hmsWirePurposeLkup] ([ReportName], [Purpose],[CreatedAt],[CreatedBy],[ModifiedBy],[ModifiedAt],[IsApproved]) VALUES('Adhoc Report', 'OTC Derivatives',GETDATE(),-1, NULL, NULL, 1)
INSERT INTO [hmsWirePurposeLkup] ([ReportName], [Purpose],[CreatedAt],[CreatedBy],[ModifiedBy],[ModifiedAt],[IsApproved]) VALUES('Adhoc Report', 'OTC Option Premiums',GETDATE(),-1, NULL, NULL, 1)
INSERT INTO [hmsWirePurposeLkup] ([ReportName], [Purpose],[CreatedAt],[CreatedBy],[ModifiedBy],[ModifiedAt],[IsApproved]) VALUES('Adhoc Report', 'PB to PB Transfer',GETDATE(),-1, NULL, NULL, 1)
INSERT INTO [hmsWirePurposeLkup] ([ReportName], [Purpose],[CreatedAt],[CreatedBy],[ModifiedBy],[ModifiedAt],[IsApproved]) VALUES('Adhoc Report', 'Private Debt Loan Payment',GETDATE(),-1, NULL, NULL, 1)
INSERT INTO [hmsWirePurposeLkup] ([ReportName], [Purpose],[CreatedAt],[CreatedBy],[ModifiedBy],[ModifiedAt],[IsApproved]) VALUES('Adhoc Report', 'Private Investment',GETDATE(),-1, NULL, NULL, 1)
INSERT INTO [hmsWirePurposeLkup] ([ReportName], [Purpose],[CreatedAt],[CreatedBy],[ModifiedBy],[ModifiedAt],[IsApproved]) VALUES('Adhoc Report', 'Redemption Payment',GETDATE(),-1, NULL, NULL, 1)
INSERT INTO [hmsWirePurposeLkup] ([ReportName], [Purpose],[CreatedAt],[CreatedBy],[ModifiedBy],[ModifiedAt],[IsApproved]) VALUES('Adhoc Report', 'Repo Margin',GETDATE(),-1, NULL, NULL, 1)
INSERT INTO [hmsWirePurposeLkup] ([ReportName], [Purpose],[CreatedAt],[CreatedBy],[ModifiedBy],[ModifiedAt],[IsApproved]) VALUES('Adhoc Report', 'Rights Offer',GETDATE(),-1, NULL, NULL, 1)
INSERT INTO [hmsWirePurposeLkup] ([ReportName], [Purpose],[CreatedAt],[CreatedBy],[ModifiedBy],[ModifiedAt],[IsApproved]) VALUES('Adhoc Report', 'Swap Payment',GETDATE(),-1, NULL, NULL, 1)
INSERT INTO [hmsWirePurposeLkup] ([ReportName], [Purpose],[CreatedAt],[CreatedBy],[ModifiedBy],[ModifiedAt],[IsApproved]) VALUES('Adhoc Report', 'Tax Payment',GETDATE(),-1, NULL, NULL, 1)
INSERT INTO [hmsWirePurposeLkup] ([ReportName], [Purpose],[CreatedAt],[CreatedBy],[ModifiedBy],[ModifiedAt],[IsApproved]) VALUES('Adhoc Report', 'Trade Related',GETDATE(),-1, NULL, NULL, 1)
INSERT INTO [hmsWirePurposeLkup] ([ReportName], [Purpose],[CreatedAt],[CreatedBy],[ModifiedBy],[ModifiedAt],[IsApproved]) VALUES('Adhoc Report', 'Tri Party',GETDATE(),-1, NULL, NULL, 1)
INSERT INTO [hmsWirePurposeLkup] ([ReportName], [Purpose],[CreatedAt],[CreatedBy],[ModifiedBy],[ModifiedAt],[IsApproved]) VALUES('Adhoc Report', 'Vendor Payment',GETDATE(),-1, NULL, NULL, 1)
END
GO