
IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'onBoardingAccount' AND COLUMN_NAME = 'TopLevelManagerAccountNumber')
BEGIN
	ALTER TABLE onBoardingAccount ADD TopLevelManagerAccountNumber VARCHAR(100)
END