IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'Status' AND TABLE_NAME = 'hmsSwiftStatusLkup')
BEGIN
	ALTER TABLE hmsSwiftStatusLkup DROP CONSTRAINT UK_hmsSwiftStatusLkup_Status;

	ALTER TABLE hmsSwiftStatusLkup ALTER COLUMN [Status] VARCHAR(30) NOT NULL ;

	ALTER TABLE [dbo].[hmsSwiftStatusLkup]  WITH CHECK ADD CONSTRAINT [UK_hmsSwiftStatusLkup_Status] UNIQUE ([Status])
END


IF NOT EXISTS(SELECT * FROM SYS.OBJECTS WHERE NAME = 'UK_hmsSwiftStatusLkup_Status')
BEGIN
	ALTER TABLE [dbo].[hmsSwiftStatusLkup]  WITH CHECK ADD CONSTRAINT [UK_hmsSwiftStatusLkup_Status] UNIQUE ([Status])
END


IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'Amount' AND TABLE_NAME = 'hmsWires')
BEGIN
	ALTER TABLE hmsWires ALTER COLUMN [Amount] DECIMAL(18,2) NOT NULL ;
END
