
IF EXISTS(SELECT 8 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'AcceptedMessages' AND TABLE_NAME = 'hmsSwiftGroup')
BEGIN
ALTER TABLE hmsSwiftGroup ALTER COLUMN AcceptedMessages VARCHAR(1000) NULL;
END
GO