IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'hmsMQLogs' AND COLUMN_NAME = 'OpsSecureHandlerMessage')
BEGIN
	ALTER TABLE hmsMQLogs ADD OpsSecureHandlerMessage VARCHAR(500)
END
