IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'AccountModule' AND TABLE_NAME = 'onBoardingAccount')
BEGIN
	ALTER TABLE dbo.onBoardingAccount ADD [AccountModule] VARCHAR(500) NULL;
END
GO

