USE HM_WIRES;
IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME= 'hmsWires' AND COLUMN_NAME = 'SystemAmount')
BEGIN
	ALTER TABLE hmsWires ADD SystemAmount DECIMAL(18,2) NOT NULL DEFAULT(0);
END
GO
