


--- Following are the columns to DROP - V 

IF EXISTS(SELECT 8 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'BeneficiaryBICorABA' AND TABLE_NAME = 'onBoardingSSITemplate') BEGIN ALTER TABLE onBoardingSSITemplate DROP COLUMN BeneficiaryBICorABA; END
IF EXISTS(SELECT 8 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'BeneficiaryBankName' AND TABLE_NAME = 'onBoardingSSITemplate') BEGIN ALTER TABLE onBoardingSSITemplate DROP COLUMN BeneficiaryBankName; END
IF EXISTS(SELECT 8 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'BeneficiaryBankAddress' AND TABLE_NAME = 'onBoardingSSITemplate') BEGIN ALTER TABLE onBoardingSSITemplate DROP COLUMN BeneficiaryBankAddress; END
IF EXISTS(SELECT 8 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'IntermediaryBICorABA' AND TABLE_NAME = 'onBoardingSSITemplate') BEGIN ALTER TABLE onBoardingSSITemplate DROP COLUMN IntermediaryBICorABA; END
IF EXISTS(SELECT 8 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'IntermediaryBankName' AND TABLE_NAME = 'onBoardingSSITemplate') BEGIN ALTER TABLE onBoardingSSITemplate DROP COLUMN IntermediaryBankName; END
IF EXISTS(SELECT 8 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'IntermediaryBankAddress' AND TABLE_NAME = 'onBoardingSSITemplate') BEGIN ALTER TABLE onBoardingSSITemplate DROP COLUMN IntermediaryBankAddress; END
IF EXISTS(SELECT 8 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'UltimateBeneficiaryBICorABA' AND TABLE_NAME = 'onBoardingSSITemplate') BEGIN ALTER TABLE onBoardingSSITemplate DROP COLUMN UltimateBeneficiaryBICorABA; END
IF EXISTS(SELECT 8 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'UltimateBeneficiaryBankName' AND TABLE_NAME = 'onBoardingSSITemplate') BEGIN ALTER TABLE onBoardingSSITemplate DROP COLUMN UltimateBeneficiaryBankName; END
IF EXISTS(SELECT 8 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'UltimateBeneficiaryBankAddress' AND TABLE_NAME = 'onBoardingSSITemplate') BEGIN ALTER TABLE onBoardingSSITemplate DROP COLUMN UltimateBeneficiaryBankAddress; END
