IF  EXISTS(SELECT 8 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'ApprovedOrRejectedAt' AND TABLE_NAME = 'hmsWires')
BEGIN
	ALTER TABLE hmsWires DROP COLUMN ApprovedOrRejectedAt  --DATETIME
END

IF  EXISTS(SELECT 8 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'ApprovedOrRejectedBy' AND TABLE_NAME = 'hmsWires')
BEGIN
	ALTER TABLE hmsWires DROP COLUMN ApprovedOrRejectedBy --INT  
END
GO

