USE HM_WIRES;


IF NOT EXISTS( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'hmsScheduleLogs' AND COLUMN_NAME = 'IsManualTrigger')
BEGIN
	ALTER TABLE hmsScheduleLogs ADD IsManualTrigger BIT NOT NULL DEFAULT 0
END

IF NOT EXISTS( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'hmsScheduleLogs' AND COLUMN_NAME = 'ExpectedScheduleStartAt')
BEGIN
	ALTER TABLE hmsScheduleLogs ADD ExpectedScheduleStartAt DATETIMEOFFSET NOT NULL DEFAULT ('2020-01-01');
END

IF NOT EXISTS( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'hmsScheduleLogs' AND COLUMN_NAME = 'ExpectedScheduleEndAt')
BEGIN
	ALTER TABLE hmsScheduleLogs ADD ExpectedScheduleEndAt DATETIMEOFFSET NOT NULL DEFAULT ('2020-01-01');
END

IF EXISTS( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'hmsScheduleLogs' AND COLUMN_NAME = 'ExpectedScheduleStartAt' AND DATA_TYPE='datetime')
BEGIN
	ALTER TABLE hmsScheduleLogs ALTER COLUMN ExpectedScheduleStartAt DATETIMEOFFSET NOT NULL;
END

IF EXISTS( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'hmsScheduleLogs' AND COLUMN_NAME = 'ScheduleStartTime')
BEGIN
	ALTER TABLE hmsScheduleLogs ALTER COLUMN ScheduleStartTime DATETIMEOFFSET NOT NULL
END

IF EXISTS( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'hmsScheduleLogs' AND COLUMN_NAME = 'ScheduleEndTime')
BEGIN
	ALTER TABLE hmsScheduleLogs ALTER COLUMN ScheduleEndTime DATETIMEOFFSET NULL
END

GO