IF EXISTS(SELECT 1 FROM SYS.COLUMNS WHERE NAME = 'IsDeleted' AND OBJECT_NAME(OBJECT_ID) = 'hmsWireJobSchedules') AND
NOT EXISTS(SELECT 1 FROM SYS.COLUMNS WHERE NAME = 'IsJobInActive' AND OBJECT_NAME(OBJECT_ID) = 'hmsWireJobSchedules')
BEGIN
EXEC SP_RENAME 'dbo.hmsWireJobSchedules.IsDeleted', 'IsJobInActive', 'COLUMN';
END