USE HM_WIRES

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'onBoardingSSITemplate' AND COLUMN_NAME = 'LastUsedAt')
BEGIN
	ALTER TABLE onBoardingSSITemplate ADD LastUsedAt DATETIME NOT NULL DEFAULT(GETDATE())
END
GO


