
IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'SwiftGroup' AND TABLE_NAME = 'hmsSwiftGroup')
BEGIN
	ALTER TABLE hmsSwiftGroup ALTER COLUMN SwiftGroup VARCHAR(200) NOT NULL;
END
GO