USE HM_WIRES


IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'hmsWires' AND COLUMN_NAME = 'OnBoardAccountId')
BEGIN
	ALTER TABLE hmsWires  ALTER COLUMN OnBoardAccountId BIGINT NOT NULL;
END


IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_NAME = 'hmsWires' AND CONSTRAINT_NAME = 'FK_hmsWires_OnBoardAccountId')
BEGIN
 	ALTER TABLE hmsWires  WITH NOCHECK ADD CONSTRAINT FK_hmsWires_OnBoardAccountId FOREIGN KEY([OnBoardAccountId])
	REFERENCES [onBoardingAccount] ([onBoardingAccountId]);
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_NAME = 'hmsWires' AND CONSTRAINT_NAME = 'FK_hmsWires_ReceivingOnBoardAccountId')
	BEGIN

	IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'hmsWires' AND COLUMN_NAME = 'ReceivingOnBoardAccountId')
	BEGIN
		ALTER TABLE hmsWires ADD ReceivingOnBoardAccountId BIGINT NULL;
	
		ALTER TABLE hmsWires  WITH NOCHECK ADD CONSTRAINT FK_hmsWires_ReceivingOnBoardAccountId FOREIGN KEY([ReceivingOnBoardAccountId])
		REFERENCES [onBoardingAccount] ([onBoardingAccountId]);		
	END
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_NAME = 'hmsWires' AND CONSTRAINT_NAME = 'FK_hmsWires_OnBoardSSITemplateId')
	BEGIN

	IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'hmsWires' AND COLUMN_NAME = 'OnBoardSSITemplateId')
	BEGIN
		ALTER TABLE hmsWires  ALTER COLUMN OnBoardSSITemplateId BIGINT NULL;

		UPDATE hmsWires SET OnBoardSSITemplateId =NULL where OnBoardSSITemplateId =0;

		ALTER TABLE hmsWires  WITH NOCHECK ADD CONSTRAINT FK_hmsWires_OnBoardSSITemplateId FOREIGN KEY([OnBoardSSITemplateId])
		REFERENCES [onBoardingSSITemplate] ([onBoardingSSITemplateId])
	END
END

GO