USE HM_WIRES;

IF EXISTS( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'hmsWireJobSchedules')
BEGIN
	IF NOT EXISTS( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'hmsWireJobSchedules' AND COLUMN_NAME = 'JobId')
	BEGIN
		ALTER TABLE hmsWireJobSchedules ADD JobId VARCHAR(100) NULL;
	END
END

IF EXISTS( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'hmsWireJobSchedules' AND COLUMN_NAME = 'IsJobCreated')
BEGIN
	EXEC sp_rename 'dbo.hmsWireJobSchedules.IsJobCreated', 'IsJobExecuted', 'COLUMN'
	UPDATE hmsWireJobSchedules SET IsJobExecuted=0 WHERE ScheduledDate >GETDATE();
END

IF EXISTS( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'hmsWireJobSchedules' AND COLUMN_NAME = 'IsJobInActive')
BEGIN
	ALTER TABLE hmsWireJobSchedules DROP COLUMN IsJobInActive
END

IF EXISTS( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'hmsWireJobSchedules' AND COLUMN_NAME = 'CreatedBy')
BEGIN
	ALTER TABLE hmsWireJobSchedules DROP COLUMN CreatedBy
END

IF EXISTS( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'hmsWireJobSchedules' AND COLUMN_NAME = 'UpdatedBy')
BEGIN
	ALTER TABLE hmsWireJobSchedules DROP COLUMN UpdatedBy
END

IF EXISTS( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'hmsWireJobSchedules')
BEGIN
	Exec sp_rename 'dbo.hmsWireJobSchedules','hmsWireAutoCancellationJobs'
	UPDATE hmsWireAutoCancellationJobs SET IsJobExecuted=0 WHERE ScheduledDate > GETDATE()
END


