IF NOT EXISTS(SELECT 8 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'hmFundId' AND TABLE_NAME = 'onBoardingAccount')
BEGIN
	ALTER TABLE onBoardingAccount ADD hmFundId BIGINT NOT NULL DEFAULT 0
END
GO