IF NOT EXISTS(SELECT 8 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'ApprovedAt' AND TABLE_NAME = 'hmsWires')
BEGIN
	ALTER TABLE hmsWires ADD ApprovedAt DATETIME 
END

IF NOT EXISTS(SELECT 8 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'ApprovedBy' AND TABLE_NAME = 'hmsWires')
BEGIN
	ALTER TABLE hmsWires ADD ApprovedBy INT  
END
GO

