USE HM_WIRES;
IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'IsAllowWireCancellation' AND TABLE_NAME = 'hmsSwiftGroup')
BEGIN
	ALTER TABLE hmsSwiftGroup ADD IsAllowWireCancellation BIT NOT NULL DEFAULT (0);
END
GO

 
      