include:
  - project: 'glb/glb-01/gl-templates'
    ref: master
    file: '/gitlab-ci/dotnetfw-ci-common-core.yml'


variables:
#  GLB_COMMON_NO_TEST: 'yes'
#  GLB_COMMON_NO_BUILD: 'yes'
 ENABLE_ANSIBLE_DEPLOYMENT: 'no'
 GIT_STRATEGY: clone
 APPSCAN_INCLUDE_FILENAMES_PATTERN: '*'
 APPSCAN_MNEMONIC: 'DMO'
 APPSCAN_PROFILENAME: '#VRA - DMO - HedgeMark Managed Account Operations'
 NEXUS_ARTIFACT_EXTENSION: 'zip'
 SOURCE_CODE_LANGUAGE: 'dotnet'
 DEPLOYMENT_HOSTS: 'wt81b10086tv00.ams.bnymellon.net:wt81b10085tv00.ams.bnymellon.net'
 VM_PLATFORM: 'windows'
 OPERATOR_ID: 'dmum76m'
 CI_ENVIRONMENT_NAME: 'test'
 JDK_ANSIBLE_JOB_TEMPLATE: '71819'
 JDK_ANSIBLE_AWX_TOKEN: 'SEFGYZmdbzSfbb6D118BpQBeCdy7q7'
 JDK_ANSIBLE_OPERATOR_ID: 'xbbn39n'
 JDK_ANSIBLE_AWX_URL: 'https://ansibletower-nonprod.bnymellon.net'
 NEXUS_REPO_ID: 'd-BNYMellon-snapshots'
 NEXUS_GROUP: 'dmo.bnym'
 NEXUS_ARTIFACT: 'HM-Ops-Secure'
 NEXUS_ARTIFACT_VERSION: '0.0.1-SNAPSHOT'
#  APPSCAN_REPOSITORY_ID: 'd-BNYMellon-snapshots'