

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'onBoardingAccount' AND COLUMN_NAME = 'IsKeyFieldsChanged')
BEGIN
	ALTER TABLE onBoardingAccount ADD IsKeyFieldsChanged BIT DEFAULT 0 NOT NULL
END