USE HM_WIRES

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'onBoardingSSITemplate' AND COLUMN_NAME = 'IsKeyFieldsChanged')
BEGIN
	ALTER TABLE onBoardingSSITemplate ADD IsKeyFieldsChanged BIT DEFAULT 0 NOT NULL
END
GO