USE HM_WIRES;

-------//hmsWiresS//--------
IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME= 'hmsWires' AND COLUMN_NAME = 'DummyClientFundId')
BEGIN
   ALTER TABLE hmsWires DROP COLUMN DummyClientFundId;
END

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME= 'onBoardingAccount' AND COLUMN_NAME = 'DummyClientFundId')
BEGIN
   ALTER TABLE onBoardingAccount DROP COLUMN DummyClientFundId;
END
